# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Enums/ChallengeFinishStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Enums/ChallengeFinishStatus.proto',
  package='WUProtos.Enums',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*WUProtos/Enums/ChallengeFinishStatus.proto\x12\x0eWUProtos.Enums*\x8d\x01\n\x15\x43hallengeFinishStatus\x12#\n\x1f\x43HALLENGE_FINISH_STATUS_UNKNOWN\x10\x00\x12&\n\"CHALLENGE_FINISH_STATUS_PLAYER_WON\x10\x01\x12\'\n#CHALLENGE_FINISH_STATUS_PLAYER_LOSE\x10\x02\x62\x06proto3')
)

_CHALLENGEFINISHSTATUS = _descriptor.EnumDescriptor(
  name='ChallengeFinishStatus',
  full_name='WUProtos.Enums.ChallengeFinishStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHALLENGE_FINISH_STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHALLENGE_FINISH_STATUS_PLAYER_WON', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHALLENGE_FINISH_STATUS_PLAYER_LOSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=63,
  serialized_end=204,
)
_sym_db.RegisterEnumDescriptor(_CHALLENGEFINISHSTATUS)

ChallengeFinishStatus = enum_type_wrapper.EnumTypeWrapper(_CHALLENGEFINISHSTATUS)
CHALLENGE_FINISH_STATUS_UNKNOWN = 0
CHALLENGE_FINISH_STATUS_PLAYER_WON = 1
CHALLENGE_FINISH_STATUS_PLAYER_LOSE = 2


DESCRIPTOR.enum_types_by_name['ChallengeFinishStatus'] = _CHALLENGEFINISHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
