# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Enums/StoryboardResetMode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Enums/StoryboardResetMode.proto',
  package='WUProtos.Enums',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(WUProtos/Enums/StoryboardResetMode.proto\x12\x0eWUProtos.Enums*\x9f\x01\n\x13StoryboardResetMode\x12\x1c\n\x18STORYBOARD_RESET_UNKNOWN\x10\x00\x12 \n\x1cSTORYBOARD_RESET_NOT_ALLOWED\x10\x01\x12$\n STORYBOARD_RESET_WHEN_INCOMPLETE\x10\x02\x12\"\n\x1eSTORYBOARD_RESET_WHEN_COMPLETE\x10\x03\x62\x06proto3')
)

_STORYBOARDRESETMODE = _descriptor.EnumDescriptor(
  name='StoryboardResetMode',
  full_name='WUProtos.Enums.StoryboardResetMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_RESET_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_RESET_NOT_ALLOWED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_RESET_WHEN_INCOMPLETE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_RESET_WHEN_COMPLETE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=61,
  serialized_end=220,
)
_sym_db.RegisterEnumDescriptor(_STORYBOARDRESETMODE)

StoryboardResetMode = enum_type_wrapper.EnumTypeWrapper(_STORYBOARDRESETMODE)
STORYBOARD_RESET_UNKNOWN = 0
STORYBOARD_RESET_NOT_ALLOWED = 1
STORYBOARD_RESET_WHEN_INCOMPLETE = 2
STORYBOARD_RESET_WHEN_COMPLETE = 3


DESCRIPTOR.enum_types_by_name['StoryboardResetMode'] = _STORYBOARDRESETMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
