# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Debug/DebugModifyCollectionItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Debug/DebugModifyCollectionItem.proto',
  package='WUProtos.Data.Debug',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n3WUProtos/Data/Debug/DebugModifyCollectionItem.proto\x12\x13WUProtos.Data.Debug\"t\n\x19\x44\x65\x62ugModifyCollectionItem\x12\n\n\x02id\x18\x01 \x01(\t\x12&\n\x1eincrement_times_encountered_by\x18\x02 \x01(\x05\x12#\n\x1bincrement_times_returned_by\x18\x03 \x01(\x05\x62\x06proto3')
)




_DEBUGMODIFYCOLLECTIONITEM = _descriptor.Descriptor(
  name='DebugModifyCollectionItem',
  full_name='WUProtos.Data.Debug.DebugModifyCollectionItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='WUProtos.Data.Debug.DebugModifyCollectionItem.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='increment_times_encountered_by', full_name='WUProtos.Data.Debug.DebugModifyCollectionItem.increment_times_encountered_by', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='increment_times_returned_by', full_name='WUProtos.Data.Debug.DebugModifyCollectionItem.increment_times_returned_by', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['DebugModifyCollectionItem'] = _DEBUGMODIFYCOLLECTIONITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DebugModifyCollectionItem = _reflection.GeneratedProtocolMessageType('DebugModifyCollectionItem', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGMODIFYCOLLECTIONITEM,
  __module__ = 'WUProtos.Data.Debug.DebugModifyCollectionItem_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Debug.DebugModifyCollectionItem)
  ))
_sym_db.RegisterMessage(DebugModifyCollectionItem)


# @@protoc_insertion_point(module_scope)
