# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Client/ClientTelemetryProfileButtonRandomize.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Enums import CategoryRandomize_pb2 as WUProtos_dot_Enums_dot_CategoryRandomize__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Client/ClientTelemetryProfileButtonRandomize.proto',
  package='WUProtos.Data.Client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n@WUProtos/Data/Client/ClientTelemetryProfileButtonRandomize.proto\x12\x14WUProtos.Data.Client\x1a&WUProtos/Enums/CategoryRandomize.proto\"\\\n%ClientTelemetryProfileButtonRandomize\x12\x33\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32!.WUProtos.Enums.CategoryRandomizeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Enums_dot_CategoryRandomize__pb2.DESCRIPTOR,])




_CLIENTTELEMETRYPROFILEBUTTONRANDOMIZE = _descriptor.Descriptor(
  name='ClientTelemetryProfileButtonRandomize',
  full_name='WUProtos.Data.Client.ClientTelemetryProfileButtonRandomize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='WUProtos.Data.Client.ClientTelemetryProfileButtonRandomize.category', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=222,
)

_CLIENTTELEMETRYPROFILEBUTTONRANDOMIZE.fields_by_name['category'].enum_type = WUProtos_dot_Enums_dot_CategoryRandomize__pb2._CATEGORYRANDOMIZE
DESCRIPTOR.message_types_by_name['ClientTelemetryProfileButtonRandomize'] = _CLIENTTELEMETRYPROFILEBUTTONRANDOMIZE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientTelemetryProfileButtonRandomize = _reflection.GeneratedProtocolMessageType('ClientTelemetryProfileButtonRandomize', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTELEMETRYPROFILEBUTTONRANDOMIZE,
  __module__ = 'WUProtos.Data.Client.ClientTelemetryProfileButtonRandomize_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Client.ClientTelemetryProfileButtonRandomize)
  ))
_sym_db.RegisterMessage(ClientTelemetryProfileButtonRandomize)


# @@protoc_insertion_point(module_scope)
