# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/data/client/client_telemetry_batch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/data/client/client_telemetry_batch.proto',
  package='wuprotos.data.client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n1wuprotos/data/client/client_telemetry_batch.proto\x12\x14wuprotos.data.client\"\xeb\x03\n\x14\x43lientTelemetryBatch\x12W\n\x12telemetry_scope_id\x18\x01 \x01(\x0e\x32;.wuprotos.data.client.ClientTelemetryBatch.TelemetryScopeId\x12P\n\x06\x65vents\x18\x02 \x03(\x0b\x32@.wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord\x12Q\n\x07metrics\x18\x03 \x03(\x0b\x32@.wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord\x12\x13\n\x0b\x61pi_version\x18\x04 \x01(\t\x12\x17\n\x0fmessage_version\x18\x05 \x01(\t\x1as\n\x15\x43lientTelemetryRecord\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x17\n\x0f\x65ncoded_message\x18\x02 \x01(\x0c\x12\x1b\n\x13\x63lient_timestamp_ms\x18\x03 \x01(\x03\x12\x11\n\tmetric_id\x18\x04 \x01(\x03\"2\n\x10TelemetryScopeId\x12\t\n\x05UNSET\x10\x00\x12\t\n\x05\x44ITTO\x10\x01\x12\x08\n\x04GAME\x10\x02\x62\x06proto3')
)



_CLIENTTELEMETRYBATCH_TELEMETRYSCOPEID = _descriptor.EnumDescriptor(
  name='TelemetryScopeId',
  full_name='wuprotos.data.client.ClientTelemetryBatch.TelemetryScopeId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DITTO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=567,
)
_sym_db.RegisterEnumDescriptor(_CLIENTTELEMETRYBATCH_TELEMETRYSCOPEID)


_CLIENTTELEMETRYBATCH_CLIENTTELEMETRYRECORD = _descriptor.Descriptor(
  name='ClientTelemetryRecord',
  full_name='wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_id', full_name='wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord.record_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoded_message', full_name='wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord.encoded_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_timestamp_ms', full_name='wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord.client_timestamp_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric_id', full_name='wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord.metric_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=515,
)

_CLIENTTELEMETRYBATCH = _descriptor.Descriptor(
  name='ClientTelemetryBatch',
  full_name='wuprotos.data.client.ClientTelemetryBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telemetry_scope_id', full_name='wuprotos.data.client.ClientTelemetryBatch.telemetry_scope_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='wuprotos.data.client.ClientTelemetryBatch.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='wuprotos.data.client.ClientTelemetryBatch.metrics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_version', full_name='wuprotos.data.client.ClientTelemetryBatch.api_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_version', full_name='wuprotos.data.client.ClientTelemetryBatch.message_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTTELEMETRYBATCH_CLIENTTELEMETRYRECORD, ],
  enum_types=[
    _CLIENTTELEMETRYBATCH_TELEMETRYSCOPEID,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=567,
)

_CLIENTTELEMETRYBATCH_CLIENTTELEMETRYRECORD.containing_type = _CLIENTTELEMETRYBATCH
_CLIENTTELEMETRYBATCH.fields_by_name['telemetry_scope_id'].enum_type = _CLIENTTELEMETRYBATCH_TELEMETRYSCOPEID
_CLIENTTELEMETRYBATCH.fields_by_name['events'].message_type = _CLIENTTELEMETRYBATCH_CLIENTTELEMETRYRECORD
_CLIENTTELEMETRYBATCH.fields_by_name['metrics'].message_type = _CLIENTTELEMETRYBATCH_CLIENTTELEMETRYRECORD
_CLIENTTELEMETRYBATCH_TELEMETRYSCOPEID.containing_type = _CLIENTTELEMETRYBATCH
DESCRIPTOR.message_types_by_name['ClientTelemetryBatch'] = _CLIENTTELEMETRYBATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientTelemetryBatch = _reflection.GeneratedProtocolMessageType('ClientTelemetryBatch', (_message.Message,), dict(

  ClientTelemetryRecord = _reflection.GeneratedProtocolMessageType('ClientTelemetryRecord', (_message.Message,), dict(
    DESCRIPTOR = _CLIENTTELEMETRYBATCH_CLIENTTELEMETRYRECORD,
    __module__ = 'wuprotos.data.client.client_telemetry_batch_pb2'
    # @@protoc_insertion_point(class_scope:wuprotos.data.client.ClientTelemetryBatch.ClientTelemetryRecord)
    ))
  ,
  DESCRIPTOR = _CLIENTTELEMETRYBATCH,
  __module__ = 'wuprotos.data.client.client_telemetry_batch_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.data.client.ClientTelemetryBatch)
  ))
_sym_db.RegisterMessage(ClientTelemetryBatch)
_sym_db.RegisterMessage(ClientTelemetryBatch.ClientTelemetryRecord)


# @@protoc_insertion_point(module_scope)
