# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Client/ClientEncounterStageCombat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Client import ClientCombatState_pb2 as WUProtos_dot_Data_dot_Client_dot_ClientCombatState__pb2
from WUProtos.Data.Client import ClientCombatEnemyTrait_pb2 as WUProtos_dot_Data_dot_Client_dot_ClientCombatEnemyTrait__pb2
from WUProtos.Data.Client import ClientEncounterType_pb2 as WUProtos_dot_Data_dot_Client_dot_ClientEncounterType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Client/ClientEncounterStageCombat.proto',
  package='WUProtos.Data.Client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n5WUProtos/Data/Client/ClientEncounterStageCombat.proto\x12\x14WUProtos.Data.Client\x1a,WUProtos/Data/Client/ClientCombatState.proto\x1a\x31WUProtos/Data/Client/ClientCombatEnemyTrait.proto\x1a.WUProtos/Data/Client/ClientEncounterType.proto\"\x83\x02\n\x1a\x43lientEncounterStageCombat\x12\x42\n\x11state_graph_nodes\x18\x01 \x03(\x0b\x32\'.WUProtos.Data.Client.ClientCombatState\x12\x42\n\x0c\x65nemy_traits\x18\x02 \x03(\x0b\x32,.WUProtos.Data.Client.ClientCombatEnemyTrait\x12\x42\n\x0f\x65nemy_rank_tags\x18\x03 \x03(\x0b\x32).WUProtos.Data.Client.ClientEncounterType\x12\x19\n\x11\x65nemy_flavor_text\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Client_dot_ClientCombatState__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Client_dot_ClientCombatEnemyTrait__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Client_dot_ClientEncounterType__pb2.DESCRIPTOR,])




_CLIENTENCOUNTERSTAGECOMBAT = _descriptor.Descriptor(
  name='ClientEncounterStageCombat',
  full_name='WUProtos.Data.Client.ClientEncounterStageCombat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_graph_nodes', full_name='WUProtos.Data.Client.ClientEncounterStageCombat.state_graph_nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemy_traits', full_name='WUProtos.Data.Client.ClientEncounterStageCombat.enemy_traits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemy_rank_tags', full_name='WUProtos.Data.Client.ClientEncounterStageCombat.enemy_rank_tags', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemy_flavor_text', full_name='WUProtos.Data.Client.ClientEncounterStageCombat.enemy_flavor_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=484,
)

_CLIENTENCOUNTERSTAGECOMBAT.fields_by_name['state_graph_nodes'].message_type = WUProtos_dot_Data_dot_Client_dot_ClientCombatState__pb2._CLIENTCOMBATSTATE
_CLIENTENCOUNTERSTAGECOMBAT.fields_by_name['enemy_traits'].message_type = WUProtos_dot_Data_dot_Client_dot_ClientCombatEnemyTrait__pb2._CLIENTCOMBATENEMYTRAIT
_CLIENTENCOUNTERSTAGECOMBAT.fields_by_name['enemy_rank_tags'].message_type = WUProtos_dot_Data_dot_Client_dot_ClientEncounterType__pb2._CLIENTENCOUNTERTYPE
DESCRIPTOR.message_types_by_name['ClientEncounterStageCombat'] = _CLIENTENCOUNTERSTAGECOMBAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientEncounterStageCombat = _reflection.GeneratedProtocolMessageType('ClientEncounterStageCombat', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTENCOUNTERSTAGECOMBAT,
  __module__ = 'WUProtos.Data.Client.ClientEncounterStageCombat_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Client.ClientEncounterStageCombat)
  ))
_sym_db.RegisterMessage(ClientEncounterStageCombat)


# @@protoc_insertion_point(module_scope)
