# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Client/ClientTelemetryCombatGameOutOfEnergyPurchaseButton.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Client/ClientTelemetryCombatGameOutOfEnergyPurchaseButton.proto',
  package='WUProtos.Data.Client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nMWUProtos/Data/Client/ClientTelemetryCombatGameOutOfEnergyPurchaseButton.proto\x12\x14WUProtos.Data.Client\"`\n2ClientTelemetryCombatGameOutOfEnergyPurchaseButton\x12\x14\n\x0cplayer_level\x18\x01 \x01(\x05\x12\x14\n\x0c\x65ncounter_id\x18\x02 \x01(\tb\x06proto3')
)




_CLIENTTELEMETRYCOMBATGAMEOUTOFENERGYPURCHASEBUTTON = _descriptor.Descriptor(
  name='ClientTelemetryCombatGameOutOfEnergyPurchaseButton',
  full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyPurchaseButton',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_level', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyPurchaseButton.player_level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyPurchaseButton.encounter_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['ClientTelemetryCombatGameOutOfEnergyPurchaseButton'] = _CLIENTTELEMETRYCOMBATGAMEOUTOFENERGYPURCHASEBUTTON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientTelemetryCombatGameOutOfEnergyPurchaseButton = _reflection.GeneratedProtocolMessageType('ClientTelemetryCombatGameOutOfEnergyPurchaseButton', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTELEMETRYCOMBATGAMEOUTOFENERGYPURCHASEBUTTON,
  __module__ = 'WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyPurchaseButton_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyPurchaseButton)
  ))
_sym_db.RegisterMessage(ClientTelemetryCombatGameOutOfEnergyPurchaseButton)


# @@protoc_insertion_point(module_scope)
