# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Client/ClientTelemetrySettingsARModeToggled.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data import ARMode_pb2 as WUProtos_dot_Data_dot_ARMode__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Client/ClientTelemetrySettingsARModeToggled.proto',
  package='WUProtos.Data.Client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n?WUProtos/Data/Client/ClientTelemetrySettingsARModeToggled.proto\x12\x14WUProtos.Data.Client\x1a\x1aWUProtos/Data/ARMode.proto\"N\n$ClientTelemetrySettingsARModeToggled\x12&\n\x07\x61r_mode\x18\x01 \x01(\x0e\x32\x15.WUProtos.Data.ARModeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_ARMode__pb2.DESCRIPTOR,])




_CLIENTTELEMETRYSETTINGSARMODETOGGLED = _descriptor.Descriptor(
  name='ClientTelemetrySettingsARModeToggled',
  full_name='WUProtos.Data.Client.ClientTelemetrySettingsARModeToggled',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ar_mode', full_name='WUProtos.Data.Client.ClientTelemetrySettingsARModeToggled.ar_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=195,
)

_CLIENTTELEMETRYSETTINGSARMODETOGGLED.fields_by_name['ar_mode'].enum_type = WUProtos_dot_Data_dot_ARMode__pb2._ARMODE
DESCRIPTOR.message_types_by_name['ClientTelemetrySettingsARModeToggled'] = _CLIENTTELEMETRYSETTINGSARMODETOGGLED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientTelemetrySettingsARModeToggled = _reflection.GeneratedProtocolMessageType('ClientTelemetrySettingsARModeToggled', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTELEMETRYSETTINGSARMODETOGGLED,
  __module__ = 'WUProtos.Data.Client.ClientTelemetrySettingsARModeToggled_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Client.ClientTelemetrySettingsARModeToggled)
  ))
_sym_db.RegisterMessage(ClientTelemetrySettingsARModeToggled)


# @@protoc_insertion_point(module_scope)
