# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Client/ClientTelemetryCombatGameOutOfEnergyDialogShown.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Client/ClientTelemetryCombatGameOutOfEnergyDialogShown.proto',
  package='WUProtos.Data.Client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nJWUProtos/Data/Client/ClientTelemetryCombatGameOutOfEnergyDialogShown.proto\x12\x14WUProtos.Data.Client\"]\n/ClientTelemetryCombatGameOutOfEnergyDialogShown\x12\x14\n\x0cplayer_level\x18\x01 \x01(\x05\x12\x14\n\x0c\x65ncounter_id\x18\x02 \x01(\tb\x06proto3')
)




_CLIENTTELEMETRYCOMBATGAMEOUTOFENERGYDIALOGSHOWN = _descriptor.Descriptor(
  name='ClientTelemetryCombatGameOutOfEnergyDialogShown',
  full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyDialogShown',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_level', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyDialogShown.player_level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyDialogShown.encounter_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['ClientTelemetryCombatGameOutOfEnergyDialogShown'] = _CLIENTTELEMETRYCOMBATGAMEOUTOFENERGYDIALOGSHOWN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientTelemetryCombatGameOutOfEnergyDialogShown = _reflection.GeneratedProtocolMessageType('ClientTelemetryCombatGameOutOfEnergyDialogShown', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTELEMETRYCOMBATGAMEOUTOFENERGYDIALOGSHOWN,
  __module__ = 'WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyDialogShown_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Client.ClientTelemetryCombatGameOutOfEnergyDialogShown)
  ))
_sym_db.RegisterMessage(ClientTelemetryCombatGameOutOfEnergyDialogShown)


# @@protoc_insertion_point(module_scope)
