# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Client/ClientTelemetryCombatGameOffensiveLockOnAttempt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Enums import CombatPhaseOutcome_pb2 as WUProtos_dot_Enums_dot_CombatPhaseOutcome__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Client/ClientTelemetryCombatGameOffensiveLockOnAttempt.proto',
  package='WUProtos.Data.Client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nJWUProtos/Data/Client/ClientTelemetryCombatGameOffensiveLockOnAttempt.proto\x12\x14WUProtos.Data.Client\x1a\'WUProtos/Enums/CombatPhaseOutcome.proto\"\xa9\x01\n/ClientTelemetryCombatGameOffensiveLockOnAttempt\x12\x14\n\x0cplayer_level\x18\x01 \x01(\x05\x12\x14\n\x0c\x65ncounter_id\x18\x02 \x01(\t\x12\x15\n\rnode_location\x18\x03 \x01(\t\x12\x33\n\x07outcome\x18\x04 \x01(\x0e\x32\".WUProtos.Enums.CombatPhaseOutcomeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Enums_dot_CombatPhaseOutcome__pb2.DESCRIPTOR,])




_CLIENTTELEMETRYCOMBATGAMEOFFENSIVELOCKONATTEMPT = _descriptor.Descriptor(
  name='ClientTelemetryCombatGameOffensiveLockOnAttempt',
  full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOffensiveLockOnAttempt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_level', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOffensiveLockOnAttempt.player_level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOffensiveLockOnAttempt.encounter_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_location', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOffensiveLockOnAttempt.node_location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outcome', full_name='WUProtos.Data.Client.ClientTelemetryCombatGameOffensiveLockOnAttempt.outcome', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=311,
)

_CLIENTTELEMETRYCOMBATGAMEOFFENSIVELOCKONATTEMPT.fields_by_name['outcome'].enum_type = WUProtos_dot_Enums_dot_CombatPhaseOutcome__pb2._COMBATPHASEOUTCOME
DESCRIPTOR.message_types_by_name['ClientTelemetryCombatGameOffensiveLockOnAttempt'] = _CLIENTTELEMETRYCOMBATGAMEOFFENSIVELOCKONATTEMPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientTelemetryCombatGameOffensiveLockOnAttempt = _reflection.GeneratedProtocolMessageType('ClientTelemetryCombatGameOffensiveLockOnAttempt', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTELEMETRYCOMBATGAMEOFFENSIVELOCKONATTEMPT,
  __module__ = 'WUProtos.Data.Client.ClientTelemetryCombatGameOffensiveLockOnAttempt_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Client.ClientTelemetryCombatGameOffensiveLockOnAttempt)
  ))
_sym_db.RegisterMessage(ClientTelemetryCombatGameOffensiveLockOnAttempt)


# @@protoc_insertion_point(module_scope)
