# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Client/ClientCombatState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Client import ClientCombatMoveType_pb2 as WUProtos_dot_Data_dot_Client_dot_ClientCombatMoveType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Client/ClientCombatState.proto',
  package='WUProtos.Data.Client',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,WUProtos/Data/Client/ClientCombatState.proto\x12\x14WUProtos.Data.Client\x1a/WUProtos/Data/Client/ClientCombatMoveType.proto\"W\n\x11\x43lientCombatState\x12\x42\n\x0epossible_moves\x18\x01 \x03(\x0b\x32*.WUProtos.Data.Client.ClientCombatMoveTypeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Client_dot_ClientCombatMoveType__pb2.DESCRIPTOR,])




_CLIENTCOMBATSTATE = _descriptor.Descriptor(
  name='ClientCombatState',
  full_name='WUProtos.Data.Client.ClientCombatState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='possible_moves', full_name='WUProtos.Data.Client.ClientCombatState.possible_moves', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=206,
)

_CLIENTCOMBATSTATE.fields_by_name['possible_moves'].message_type = WUProtos_dot_Data_dot_Client_dot_ClientCombatMoveType__pb2._CLIENTCOMBATMOVETYPE
DESCRIPTOR.message_types_by_name['ClientCombatState'] = _CLIENTCOMBATSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientCombatState = _reflection.GeneratedProtocolMessageType('ClientCombatState', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTCOMBATSTATE,
  __module__ = 'WUProtos.Data.Client.ClientCombatState_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Client.ClientCombatState)
  ))
_sym_db.RegisterMessage(ClientCombatState)


# @@protoc_insertion_point(module_scope)
