# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Platform/Responses/RedeemPasscodeResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Platform/Responses/RedeemPasscodeResponse.proto',
  package='WUProtos.Networking.Platform.Responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nCWUProtos/Networking/Platform/Responses/RedeemPasscodeResponse.proto\x12&WUProtos.Networking.Platform.Responses\"\x95\x03\n\x16RedeemPasscodeResponse\x12U\n\x06result\x18\x01 \x01(\x0e\x32\x45.WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.Result\x12\x62\n\racquired_item\x18\x02 \x03(\x0b\x32K.WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.AcquiredItem\x12\x1c\n\x14\x61\x63quired_items_proto\x18\x03 \x01(\x0c\x12\x10\n\x08passcode\x18\x04 \x01(\t\x1a+\n\x0c\x41\x63quiredItem\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"c\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rNOT_AVAILABLE\x10\x02\x12\x18\n\x14OVER_INVENTORY_LIMIT\x10\x03\x12\x14\n\x10\x41LREADY_REDEEMED\x10\x04\x62\x06proto3')
)



_REDEEMPASSCODERESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_AVAILABLE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OVER_INVENTORY_LIMIT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_REDEEMED', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=418,
  serialized_end=517,
)
_sym_db.RegisterEnumDescriptor(_REDEEMPASSCODERESPONSE_RESULT)


_REDEEMPASSCODERESPONSE_ACQUIREDITEM = _descriptor.Descriptor(
  name='AcquiredItem',
  full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.AcquiredItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.AcquiredItem.item', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.AcquiredItem.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=416,
)

_REDEEMPASSCODERESPONSE = _descriptor.Descriptor(
  name='RedeemPasscodeResponse',
  full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acquired_item', full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.acquired_item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acquired_items_proto', full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.acquired_items_proto', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passcode', full_name='WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.passcode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REDEEMPASSCODERESPONSE_ACQUIREDITEM, ],
  enum_types=[
    _REDEEMPASSCODERESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=517,
)

_REDEEMPASSCODERESPONSE_ACQUIREDITEM.containing_type = _REDEEMPASSCODERESPONSE
_REDEEMPASSCODERESPONSE.fields_by_name['result'].enum_type = _REDEEMPASSCODERESPONSE_RESULT
_REDEEMPASSCODERESPONSE.fields_by_name['acquired_item'].message_type = _REDEEMPASSCODERESPONSE_ACQUIREDITEM
_REDEEMPASSCODERESPONSE_RESULT.containing_type = _REDEEMPASSCODERESPONSE
DESCRIPTOR.message_types_by_name['RedeemPasscodeResponse'] = _REDEEMPASSCODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RedeemPasscodeResponse = _reflection.GeneratedProtocolMessageType('RedeemPasscodeResponse', (_message.Message,), dict(

  AcquiredItem = _reflection.GeneratedProtocolMessageType('AcquiredItem', (_message.Message,), dict(
    DESCRIPTOR = _REDEEMPASSCODERESPONSE_ACQUIREDITEM,
    __module__ = 'WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse_pb2'
    # @@protoc_insertion_point(class_scope:WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse.AcquiredItem)
    ))
  ,
  DESCRIPTOR = _REDEEMPASSCODERESPONSE,
  __module__ = 'WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Platform.Responses.RedeemPasscodeResponse)
  ))
_sym_db.RegisterMessage(RedeemPasscodeResponse)
_sym_db.RegisterMessage(RedeemPasscodeResponse.AcquiredItem)


# @@protoc_insertion_point(module_scope)
