# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Inventory/InventoryItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Inventory/InventoryItem.proto',
  package='WUProtos.Inventory',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&WUProtos/Inventory/InventoryItem.proto\x12\x12WUProtos.Inventory\"h\n\rInventoryItem\x12\x1a\n\x12modified_timestamp\x18\x01 \x01(\x03\x12\x1a\n\x10\x64\x65leted_item_key\x18\x02 \x01(\x0cH\x00\x12\x0e\n\x04item\x18\x03 \x01(\x0cH\x00\x42\x0f\n\rInventoryItemb\x06proto3')
)




_INVENTORYITEM = _descriptor.Descriptor(
  name='InventoryItem',
  full_name='WUProtos.Inventory.InventoryItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modified_timestamp', full_name='WUProtos.Inventory.InventoryItem.modified_timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted_item_key', full_name='WUProtos.Inventory.InventoryItem.deleted_item_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item', full_name='WUProtos.Inventory.InventoryItem.item', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='InventoryItem', full_name='WUProtos.Inventory.InventoryItem.InventoryItem',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=62,
  serialized_end=166,
)

_INVENTORYITEM.oneofs_by_name['InventoryItem'].fields.append(
  _INVENTORYITEM.fields_by_name['deleted_item_key'])
_INVENTORYITEM.fields_by_name['deleted_item_key'].containing_oneof = _INVENTORYITEM.oneofs_by_name['InventoryItem']
_INVENTORYITEM.oneofs_by_name['InventoryItem'].fields.append(
  _INVENTORYITEM.fields_by_name['item'])
_INVENTORYITEM.fields_by_name['item'].containing_oneof = _INVENTORYITEM.oneofs_by_name['InventoryItem']
DESCRIPTOR.message_types_by_name['InventoryItem'] = _INVENTORYITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InventoryItem = _reflection.GeneratedProtocolMessageType('InventoryItem', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYITEM,
  __module__ = 'WUProtos.Inventory.InventoryItem_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Inventory.InventoryItem)
  ))
_sym_db.RegisterMessage(InventoryItem)


# @@protoc_insertion_point(module_scope)
