# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Inventory/InventoryFeatureFlags.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Inventory import InventoryFeatureFlag_pb2 as WUProtos_dot_Inventory_dot_InventoryFeatureFlag__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Inventory/InventoryFeatureFlags.proto',
  package='WUProtos.Inventory',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.WUProtos/Inventory/InventoryFeatureFlags.proto\x12\x12WUProtos.Inventory\x1a-WUProtos/Inventory/InventoryFeatureFlag.proto\"\\\n\x15InventoryFeatureFlags\x12\n\n\x02id\x18\x01 \x01(\t\x12\x37\n\x05\x66lags\x18\x02 \x03(\x0b\x32(.WUProtos.Inventory.InventoryFeatureFlagb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Inventory_dot_InventoryFeatureFlag__pb2.DESCRIPTOR,])




_INVENTORYFEATUREFLAGS = _descriptor.Descriptor(
  name='InventoryFeatureFlags',
  full_name='WUProtos.Inventory.InventoryFeatureFlags',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='WUProtos.Inventory.InventoryFeatureFlags.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='WUProtos.Inventory.InventoryFeatureFlags.flags', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=209,
)

_INVENTORYFEATUREFLAGS.fields_by_name['flags'].message_type = WUProtos_dot_Inventory_dot_InventoryFeatureFlag__pb2._INVENTORYFEATUREFLAG
DESCRIPTOR.message_types_by_name['InventoryFeatureFlags'] = _INVENTORYFEATUREFLAGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InventoryFeatureFlags = _reflection.GeneratedProtocolMessageType('InventoryFeatureFlags', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYFEATUREFLAGS,
  __module__ = 'WUProtos.Inventory.InventoryFeatureFlags_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Inventory.InventoryFeatureFlags)
  ))
_sym_db.RegisterMessage(InventoryFeatureFlags)


# @@protoc_insertion_point(module_scope)
