# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Inventory/InventoryCauldronSlot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Loot import LootCollection_pb2 as WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Inventory/InventoryCauldronSlot.proto',
  package='WUProtos.Inventory',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.WUProtos/Inventory/InventoryCauldronSlot.proto\x12\x12WUProtos.Inventory\x1a\'WUProtos/Data/Loot/LootCollection.proto\"\x96\x01\n\x15InventoryCauldronSlot\x12\x33\n\x07rewards\x18\x01 \x01(\x0b\x32\".WUProtos.Data.Loot.LootCollection\x12\x14\n\x0ctime_to_brew\x18\x02 \x01(\x03\x12\x15\n\rrecipe_gmt_id\x18\x03 \x01(\t\x12\x1b\n\x13master_note_applied\x18\x04 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2.DESCRIPTOR,])




_INVENTORYCAULDRONSLOT = _descriptor.Descriptor(
  name='InventoryCauldronSlot',
  full_name='WUProtos.Inventory.InventoryCauldronSlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rewards', full_name='WUProtos.Inventory.InventoryCauldronSlot.rewards', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_to_brew', full_name='WUProtos.Inventory.InventoryCauldronSlot.time_to_brew', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recipe_gmt_id', full_name='WUProtos.Inventory.InventoryCauldronSlot.recipe_gmt_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='master_note_applied', full_name='WUProtos.Inventory.InventoryCauldronSlot.master_note_applied', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=262,
)

_INVENTORYCAULDRONSLOT.fields_by_name['rewards'].message_type = WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2._LOOTCOLLECTION
DESCRIPTOR.message_types_by_name['InventoryCauldronSlot'] = _INVENTORYCAULDRONSLOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InventoryCauldronSlot = _reflection.GeneratedProtocolMessageType('InventoryCauldronSlot', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYCAULDRONSLOT,
  __module__ = 'WUProtos.Inventory.InventoryCauldronSlot_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Inventory.InventoryCauldronSlot)
  ))
_sym_db.RegisterMessage(InventoryCauldronSlot)


# @@protoc_insertion_point(module_scope)
