# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/data/ar_mode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/data/ar_mode.proto',
  package='wuprotos.data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bwuprotos/data/ar_mode.proto\x12\rwuprotos.data*?\n\x06\x41RMode\x12\x11\n\rAR_MODE_UNSET\x10\x00\x12\x0c\n\x08\x61\x64vanced\x10\x01\x12\n\n\x06simple\x10\x02\x12\x08\n\x04park\x10\x03\x62\x06proto3')
)

_ARMODE = _descriptor.EnumDescriptor(
  name='ARMode',
  full_name='wuprotos.data.ARMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AR_MODE_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='advanced', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='simple', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='park', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=46,
  serialized_end=109,
)
_sym_db.RegisterEnumDescriptor(_ARMODE)

ARMode = enum_type_wrapper.EnumTypeWrapper(_ARMODE)
AR_MODE_UNSET = 0
advanced = 1
simple = 2
park = 3


DESCRIPTOR.enum_types_by_name['ARMode'] = _ARMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
