# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/BatterySaverProfile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/BatterySaverProfile.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'WUProtos/Data/BatterySaverProfile.proto\x12\rWUProtos.Data\"5\n\x13\x42\x61tterySaverProfile\x12\x10\n\x08profiles\x18\x01 \x03(\t\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
)




_BATTERYSAVERPROFILE = _descriptor.Descriptor(
  name='BatterySaverProfile',
  full_name='WUProtos.Data.BatterySaverProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profiles', full_name='WUProtos.Data.BatterySaverProfile.profiles', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='WUProtos.Data.BatterySaverProfile.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['BatterySaverProfile'] = _BATTERYSAVERPROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatterySaverProfile = _reflection.GeneratedProtocolMessageType('BatterySaverProfile', (_message.Message,), dict(
  DESCRIPTOR = _BATTERYSAVERPROFILE,
  __module__ = 'WUProtos.Data.BatterySaverProfile_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.BatterySaverProfile)
  ))
_sym_db.RegisterMessage(BatterySaverProfile)


# @@protoc_insertion_point(module_scope)
