# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/BonusMetadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Potion import PotionBonusMetadata_pb2 as WUProtos_dot_Data_dot_Potion_dot_PotionBonusMetadata__pb2
from WUProtos.Data import WrackspurtBonusMetadata_pb2 as WUProtos_dot_Data_dot_WrackspurtBonusMetadata__pb2
from WUProtos.Data import FirstTimeCollectionBonusMetadata_pb2 as WUProtos_dot_Data_dot_FirstTimeCollectionBonusMetadata__pb2
from WUProtos.Data.Challenge import ChallengeBonus_pb2 as WUProtos_dot_Data_dot_Challenge_dot_ChallengeBonus__pb2
from WUProtos.Data import SpellGameBonusMetadata_pb2 as WUProtos_dot_Data_dot_SpellGameBonusMetadata__pb2
from WUProtos.Data.Challenge import ChallengeBonusMetadata_pb2 as WUProtos_dot_Data_dot_Challenge_dot_ChallengeBonusMetadata__pb2
from WUProtos.Data import ShardConversionBonusMetadata_pb2 as WUProtos_dot_Data_dot_ShardConversionBonusMetadata__pb2
from WUProtos.Data.Challenge import ChallengeChamberBonusMetadata_pb2 as WUProtos_dot_Data_dot_Challenge_dot_ChallengeChamberBonusMetadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/BonusMetadata.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!WUProtos/Data/BonusMetadata.proto\x12\rWUProtos.Data\x1a.WUProtos/Data/Potion/PotionBonusMetadata.proto\x1a+WUProtos/Data/WrackspurtBonusMetadata.proto\x1a\x34WUProtos/Data/FirstTimeCollectionBonusMetadata.proto\x1a,WUProtos/Data/Challenge/ChallengeBonus.proto\x1a*WUProtos/Data/SpellGameBonusMetadata.proto\x1a\x34WUProtos/Data/Challenge/ChallengeBonusMetadata.proto\x1a\x30WUProtos/Data/ShardConversionBonusMetadata.proto\x1a;WUProtos/Data/Challenge/ChallengeChamberBonusMetadata.proto\"\xd7\x04\n\rBonusMetadata\x12;\n\x06potion\x18\x01 \x01(\x0b\x32).WUProtos.Data.Potion.PotionBonusMetadataH\x00\x12<\n\nwrackspurt\x18\x02 \x01(\x0b\x32&.WUProtos.Data.WrackspurtBonusMetadataH\x00\x12P\n\x15\x66irst_time_collection\x18\x03 \x01(\x0b\x32/.WUProtos.Data.FirstTimeCollectionBonusMetadataH\x00\x12<\n\tchallenge\x18\x04 \x01(\x0b\x32\'.WUProtos.Data.Challenge.ChallengeBonusH\x00\x12;\n\nspell_game\x18\x05 \x01(\x0b\x32%.WUProtos.Data.SpellGameBonusMetadataH\x00\x12J\n\x0f\x63hallenge_bonus\x18\x06 \x01(\x0b\x32/.WUProtos.Data.Challenge.ChallengeBonusMetadataH\x00\x12G\n\x10shard_conversion\x18\x07 \x01(\x0b\x32+.WUProtos.Data.ShardConversionBonusMetadataH\x00\x12Y\n\x17\x63hallenge_chamber_bonus\x18\x08 \x01(\x0b\x32\x36.WUProtos.Data.Challenge.ChallengeChamberBonusMetadataH\x00\x42\x0e\n\x0cMetadataTypeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Potion_dot_PotionBonusMetadata__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_WrackspurtBonusMetadata__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_FirstTimeCollectionBonusMetadata__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Challenge_dot_ChallengeBonus__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_SpellGameBonusMetadata__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Challenge_dot_ChallengeBonusMetadata__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_ShardConversionBonusMetadata__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Challenge_dot_ChallengeChamberBonusMetadata__pb2.DESCRIPTOR,])




_BONUSMETADATA = _descriptor.Descriptor(
  name='BonusMetadata',
  full_name='WUProtos.Data.BonusMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='potion', full_name='WUProtos.Data.BonusMetadata.potion', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrackspurt', full_name='WUProtos.Data.BonusMetadata.wrackspurt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_time_collection', full_name='WUProtos.Data.BonusMetadata.first_time_collection', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='challenge', full_name='WUProtos.Data.BonusMetadata.challenge', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spell_game', full_name='WUProtos.Data.BonusMetadata.spell_game', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='challenge_bonus', full_name='WUProtos.Data.BonusMetadata.challenge_bonus', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shard_conversion', full_name='WUProtos.Data.BonusMetadata.shard_conversion', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='challenge_chamber_bonus', full_name='WUProtos.Data.BonusMetadata.challenge_chamber_bonus', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MetadataType', full_name='WUProtos.Data.BonusMetadata.MetadataType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=455,
  serialized_end=1054,
)

_BONUSMETADATA.fields_by_name['potion'].message_type = WUProtos_dot_Data_dot_Potion_dot_PotionBonusMetadata__pb2._POTIONBONUSMETADATA
_BONUSMETADATA.fields_by_name['wrackspurt'].message_type = WUProtos_dot_Data_dot_WrackspurtBonusMetadata__pb2._WRACKSPURTBONUSMETADATA
_BONUSMETADATA.fields_by_name['first_time_collection'].message_type = WUProtos_dot_Data_dot_FirstTimeCollectionBonusMetadata__pb2._FIRSTTIMECOLLECTIONBONUSMETADATA
_BONUSMETADATA.fields_by_name['challenge'].message_type = WUProtos_dot_Data_dot_Challenge_dot_ChallengeBonus__pb2._CHALLENGEBONUS
_BONUSMETADATA.fields_by_name['spell_game'].message_type = WUProtos_dot_Data_dot_SpellGameBonusMetadata__pb2._SPELLGAMEBONUSMETADATA
_BONUSMETADATA.fields_by_name['challenge_bonus'].message_type = WUProtos_dot_Data_dot_Challenge_dot_ChallengeBonusMetadata__pb2._CHALLENGEBONUSMETADATA
_BONUSMETADATA.fields_by_name['shard_conversion'].message_type = WUProtos_dot_Data_dot_ShardConversionBonusMetadata__pb2._SHARDCONVERSIONBONUSMETADATA
_BONUSMETADATA.fields_by_name['challenge_chamber_bonus'].message_type = WUProtos_dot_Data_dot_Challenge_dot_ChallengeChamberBonusMetadata__pb2._CHALLENGECHAMBERBONUSMETADATA
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['potion'])
_BONUSMETADATA.fields_by_name['potion'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['wrackspurt'])
_BONUSMETADATA.fields_by_name['wrackspurt'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['first_time_collection'])
_BONUSMETADATA.fields_by_name['first_time_collection'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['challenge'])
_BONUSMETADATA.fields_by_name['challenge'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['spell_game'])
_BONUSMETADATA.fields_by_name['spell_game'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['challenge_bonus'])
_BONUSMETADATA.fields_by_name['challenge_bonus'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['shard_conversion'])
_BONUSMETADATA.fields_by_name['shard_conversion'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
_BONUSMETADATA.oneofs_by_name['MetadataType'].fields.append(
  _BONUSMETADATA.fields_by_name['challenge_chamber_bonus'])
_BONUSMETADATA.fields_by_name['challenge_chamber_bonus'].containing_oneof = _BONUSMETADATA.oneofs_by_name['MetadataType']
DESCRIPTOR.message_types_by_name['BonusMetadata'] = _BONUSMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BonusMetadata = _reflection.GeneratedProtocolMessageType('BonusMetadata', (_message.Message,), dict(
  DESCRIPTOR = _BONUSMETADATA,
  __module__ = 'WUProtos.Data.BonusMetadata_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.BonusMetadata)
  ))
_sym_db.RegisterMessage(BonusMetadata)


# @@protoc_insertion_point(module_scope)
