# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/CollectStickersQuestTask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/CollectStickersQuestTask.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,WUProtos/Data/CollectStickersQuestTask.proto\x12\rWUProtos.Data\"\x8e\x01\n\x18\x43ollectStickersQuestTask\x12\x1e\n\x16required_collect_count\x18\x01 \x01(\x03\x12\x16\n\x0esticker_gmt_id\x18\x02 \x01(\t\x12\x1b\n\x13sticker_page_gmt_id\x18\x03 \x01(\t\x12\x1d\n\x15sticker_family_gmt_id\x18\x04 \x01(\tb\x06proto3')
)




_COLLECTSTICKERSQUESTTASK = _descriptor.Descriptor(
  name='CollectStickersQuestTask',
  full_name='WUProtos.Data.CollectStickersQuestTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='required_collect_count', full_name='WUProtos.Data.CollectStickersQuestTask.required_collect_count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sticker_gmt_id', full_name='WUProtos.Data.CollectStickersQuestTask.sticker_gmt_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sticker_page_gmt_id', full_name='WUProtos.Data.CollectStickersQuestTask.sticker_page_gmt_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sticker_family_gmt_id', full_name='WUProtos.Data.CollectStickersQuestTask.sticker_family_gmt_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['CollectStickersQuestTask'] = _COLLECTSTICKERSQUESTTASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CollectStickersQuestTask = _reflection.GeneratedProtocolMessageType('CollectStickersQuestTask', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTSTICKERSQUESTTASK,
  __module__ = 'WUProtos.Data.CollectStickersQuestTask_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.CollectStickersQuestTask)
  ))
_sym_db.RegisterMessage(CollectStickersQuestTask)


# @@protoc_insertion_point(module_scope)
