# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/DoEncounterHookQuestProgress.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/DoEncounterHookQuestProgress.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n0WUProtos/Data/DoEncounterHookQuestProgress.proto\x12\rWUProtos.Data\"9\n\x1c\x44oEncounterHookQuestProgress\x12\x19\n\x11\x63urrent_win_count\x18\x01 \x01(\x03\x62\x06proto3')
)




_DOENCOUNTERHOOKQUESTPROGRESS = _descriptor.Descriptor(
  name='DoEncounterHookQuestProgress',
  full_name='WUProtos.Data.DoEncounterHookQuestProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_win_count', full_name='WUProtos.Data.DoEncounterHookQuestProgress.current_win_count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['DoEncounterHookQuestProgress'] = _DOENCOUNTERHOOKQUESTPROGRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoEncounterHookQuestProgress = _reflection.GeneratedProtocolMessageType('DoEncounterHookQuestProgress', (_message.Message,), dict(
  DESCRIPTOR = _DOENCOUNTERHOOKQUESTPROGRESS,
  __module__ = 'WUProtos.Data.DoEncounterHookQuestProgress_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.DoEncounterHookQuestProgress)
  ))
_sym_db.RegisterMessage(DoEncounterHookQuestProgress)


# @@protoc_insertion_point(module_scope)
