# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/QuestTask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data import RequirementsQuestTask_pb2 as WUProtos_dot_Data_dot_RequirementsQuestTask__pb2
from WUProtos.Data import HookQuestTask_pb2 as WUProtos_dot_Data_dot_HookQuestTask__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/QuestTask.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dWUProtos/Data/QuestTask.proto\x12\rWUProtos.Data\x1a)WUProtos/Data/RequirementsQuestTask.proto\x1a!WUProtos/Data/HookQuestTask.proto\"\x80\x01\n\tQuestTask\x12\x38\n\x08req_task\x18\x01 \x01(\x0b\x32$.WUProtos.Data.RequirementsQuestTaskH\x00\x12\x31\n\thook_task\x18\x02 \x01(\x0b\x32\x1c.WUProtos.Data.HookQuestTaskH\x00\x42\x06\n\x04Typeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_RequirementsQuestTask__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_HookQuestTask__pb2.DESCRIPTOR,])




_QUESTTASK = _descriptor.Descriptor(
  name='QuestTask',
  full_name='WUProtos.Data.QuestTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_task', full_name='WUProtos.Data.QuestTask.req_task', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hook_task', full_name='WUProtos.Data.QuestTask.hook_task', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Type', full_name='WUProtos.Data.QuestTask.Type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=127,
  serialized_end=255,
)

_QUESTTASK.fields_by_name['req_task'].message_type = WUProtos_dot_Data_dot_RequirementsQuestTask__pb2._REQUIREMENTSQUESTTASK
_QUESTTASK.fields_by_name['hook_task'].message_type = WUProtos_dot_Data_dot_HookQuestTask__pb2._HOOKQUESTTASK
_QUESTTASK.oneofs_by_name['Type'].fields.append(
  _QUESTTASK.fields_by_name['req_task'])
_QUESTTASK.fields_by_name['req_task'].containing_oneof = _QUESTTASK.oneofs_by_name['Type']
_QUESTTASK.oneofs_by_name['Type'].fields.append(
  _QUESTTASK.fields_by_name['hook_task'])
_QUESTTASK.fields_by_name['hook_task'].containing_oneof = _QUESTTASK.oneofs_by_name['Type']
DESCRIPTOR.message_types_by_name['QuestTask'] = _QUESTTASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuestTask = _reflection.GeneratedProtocolMessageType('QuestTask', (_message.Message,), dict(
  DESCRIPTOR = _QUESTTASK,
  __module__ = 'WUProtos.Data.QuestTask_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.QuestTask)
  ))
_sym_db.RegisterMessage(QuestTask)


# @@protoc_insertion_point(module_scope)
