# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/data/sound_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wuprotos.data import audio_parameter_pb2 as wuprotos_dot_data_dot_audio__parameter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/data/sound_config.proto',
  package='wuprotos.data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n wuprotos/data/sound_config.proto\x12\rwuprotos.data\x1a#wuprotos/data/audio_parameter.proto\"i\n\x0bSoundConfig\x12\x12\n\nsound_bank\x18\x01 \x01(\t\x12\x13\n\x0bsound_event\x18\x02 \x01(\t\x12\x31\n\nparameters\x18\x03 \x03(\x0b\x32\x1d.wuprotos.data.AudioParameterb\x06proto3')
  ,
  dependencies=[wuprotos_dot_data_dot_audio__parameter__pb2.DESCRIPTOR,])




_SOUNDCONFIG = _descriptor.Descriptor(
  name='SoundConfig',
  full_name='wuprotos.data.SoundConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sound_bank', full_name='wuprotos.data.SoundConfig.sound_bank', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sound_event', full_name='wuprotos.data.SoundConfig.sound_event', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='wuprotos.data.SoundConfig.parameters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=193,
)

_SOUNDCONFIG.fields_by_name['parameters'].message_type = wuprotos_dot_data_dot_audio__parameter__pb2._AUDIOPARAMETER
DESCRIPTOR.message_types_by_name['SoundConfig'] = _SOUNDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SoundConfig = _reflection.GeneratedProtocolMessageType('SoundConfig', (_message.Message,), dict(
  DESCRIPTOR = _SOUNDCONFIG,
  __module__ = 'wuprotos.data.sound_config_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.data.SoundConfig)
  ))
_sym_db.RegisterMessage(SoundConfig)


# @@protoc_insertion_point(module_scope)
