# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Spell.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Spell.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19WUProtos/Data/Spell.proto\x12\rWUProtos.Data\"\xf1\x01\n\x05Spell\x12\n\n\x02id\x18\x01 \x01(\t\x12\x36\n\ttimelines\x18\x02 \x03(\x0b\x32#.WUProtos.Data.Spell.TimelinesEntry\x12=\n\rcritical_hits\x18\x03 \x03(\x0b\x32&.WUProtos.Data.Spell.CriticalHitsEntry\x1a\x30\n\x0eTimelinesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x33\n\x11\x43riticalHitsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_SPELL_TIMELINESENTRY = _descriptor.Descriptor(
  name='TimelinesEntry',
  full_name='WUProtos.Data.Spell.TimelinesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='WUProtos.Data.Spell.TimelinesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='WUProtos.Data.Spell.TimelinesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=233,
)

_SPELL_CRITICALHITSENTRY = _descriptor.Descriptor(
  name='CriticalHitsEntry',
  full_name='WUProtos.Data.Spell.CriticalHitsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='WUProtos.Data.Spell.CriticalHitsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='WUProtos.Data.Spell.CriticalHitsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=286,
)

_SPELL = _descriptor.Descriptor(
  name='Spell',
  full_name='WUProtos.Data.Spell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='WUProtos.Data.Spell.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timelines', full_name='WUProtos.Data.Spell.timelines', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='critical_hits', full_name='WUProtos.Data.Spell.critical_hits', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SPELL_TIMELINESENTRY, _SPELL_CRITICALHITSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=286,
)

_SPELL_TIMELINESENTRY.containing_type = _SPELL
_SPELL_CRITICALHITSENTRY.containing_type = _SPELL
_SPELL.fields_by_name['timelines'].message_type = _SPELL_TIMELINESENTRY
_SPELL.fields_by_name['critical_hits'].message_type = _SPELL_CRITICALHITSENTRY
DESCRIPTOR.message_types_by_name['Spell'] = _SPELL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Spell = _reflection.GeneratedProtocolMessageType('Spell', (_message.Message,), dict(

  TimelinesEntry = _reflection.GeneratedProtocolMessageType('TimelinesEntry', (_message.Message,), dict(
    DESCRIPTOR = _SPELL_TIMELINESENTRY,
    __module__ = 'WUProtos.Data.Spell_pb2'
    # @@protoc_insertion_point(class_scope:WUProtos.Data.Spell.TimelinesEntry)
    ))
  ,

  CriticalHitsEntry = _reflection.GeneratedProtocolMessageType('CriticalHitsEntry', (_message.Message,), dict(
    DESCRIPTOR = _SPELL_CRITICALHITSENTRY,
    __module__ = 'WUProtos.Data.Spell_pb2'
    # @@protoc_insertion_point(class_scope:WUProtos.Data.Spell.CriticalHitsEntry)
    ))
  ,
  DESCRIPTOR = _SPELL,
  __module__ = 'WUProtos.Data.Spell_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Spell)
  ))
_sym_db.RegisterMessage(Spell)
_sym_db.RegisterMessage(Spell.TimelinesEntry)
_sym_db.RegisterMessage(Spell.CriticalHitsEntry)


_SPELL_TIMELINESENTRY._options = None
_SPELL_CRITICALHITSENTRY._options = None
# @@protoc_insertion_point(module_scope)
