# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/StoreRarity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data import Color_pb2 as WUProtos_dot_Data_dot_Color__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/StoreRarity.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fWUProtos/Data/StoreRarity.proto\x12\rWUProtos.Data\x1a\x19WUProtos/Data/Color.proto\"R\n\x0bStoreRarity\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\ntext_color\x18\x02 \x01(\x0b\x32\x14.WUProtos.Data.Color\x12\r\n\x05title\x18\x03 \x01(\tb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Color__pb2.DESCRIPTOR,])




_STORERARITY = _descriptor.Descriptor(
  name='StoreRarity',
  full_name='WUProtos.Data.StoreRarity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='WUProtos.Data.StoreRarity.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_color', full_name='WUProtos.Data.StoreRarity.text_color', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='WUProtos.Data.StoreRarity.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=159,
)

_STORERARITY.fields_by_name['text_color'].message_type = WUProtos_dot_Data_dot_Color__pb2._COLOR
DESCRIPTOR.message_types_by_name['StoreRarity'] = _STORERARITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoreRarity = _reflection.GeneratedProtocolMessageType('StoreRarity', (_message.Message,), dict(
  DESCRIPTOR = _STORERARITY,
  __module__ = 'WUProtos.Data.StoreRarity_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.StoreRarity)
  ))
_sym_db.RegisterMessage(StoreRarity)


# @@protoc_insertion_point(module_scope)
