# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/TeamPropertyCondition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Enums import ComparisonOperator_pb2 as WUProtos_dot_Enums_dot_ComparisonOperator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/TeamPropertyCondition.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)WUProtos/Data/TeamPropertyCondition.proto\x12\rWUProtos.Data\x1a\'WUProtos/Enums/ComparisonOperator.proto\"\x90\x02\n\x15TeamPropertyCondition\x12?\n\x13\x63omparison_operator\x18\x01 \x01(\x0e\x32\".WUProtos.Enums.ComparisonOperator\x12\x1f\n\x17target_comparison_value\x18\x02 \x01(\x05\x12?\n\x08\x63riteria\x18\x03 \x01(\x0e\x32-.WUProtos.Data.TeamPropertyCondition.Criteria\"T\n\x08\x43riteria\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x46RIENDS\x10\x01\x12\x0f\n\x0bNON_FRIENDS\x10\x02\x12\r\n\tSAME_TEAM\x10\x03\x12\x0e\n\nOTHER_TEAM\x10\x04\x62\x06proto3')
  ,
  dependencies=[WUProtos_dot_Enums_dot_ComparisonOperator__pb2.DESCRIPTOR,])



_TEAMPROPERTYCONDITION_CRITERIA = _descriptor.EnumDescriptor(
  name='Criteria',
  full_name='WUProtos.Data.TeamPropertyCondition.Criteria',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRIENDS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NON_FRIENDS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAME_TEAM', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER_TEAM', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=290,
  serialized_end=374,
)
_sym_db.RegisterEnumDescriptor(_TEAMPROPERTYCONDITION_CRITERIA)


_TEAMPROPERTYCONDITION = _descriptor.Descriptor(
  name='TeamPropertyCondition',
  full_name='WUProtos.Data.TeamPropertyCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comparison_operator', full_name='WUProtos.Data.TeamPropertyCondition.comparison_operator', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_comparison_value', full_name='WUProtos.Data.TeamPropertyCondition.target_comparison_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='criteria', full_name='WUProtos.Data.TeamPropertyCondition.criteria', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TEAMPROPERTYCONDITION_CRITERIA,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=374,
)

_TEAMPROPERTYCONDITION.fields_by_name['comparison_operator'].enum_type = WUProtos_dot_Enums_dot_ComparisonOperator__pb2._COMPARISONOPERATOR
_TEAMPROPERTYCONDITION.fields_by_name['criteria'].enum_type = _TEAMPROPERTYCONDITION_CRITERIA
_TEAMPROPERTYCONDITION_CRITERIA.containing_type = _TEAMPROPERTYCONDITION
DESCRIPTOR.message_types_by_name['TeamPropertyCondition'] = _TEAMPROPERTYCONDITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamPropertyCondition = _reflection.GeneratedProtocolMessageType('TeamPropertyCondition', (_message.Message,), dict(
  DESCRIPTOR = _TEAMPROPERTYCONDITION,
  __module__ = 'WUProtos.Data.TeamPropertyCondition_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.TeamPropertyCondition)
  ))
_sym_db.RegisterMessage(TeamPropertyCondition)


# @@protoc_insertion_point(module_scope)
