# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/VaultItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data import CurrencyVaultItem_pb2 as WUProtos_dot_Data_dot_CurrencyVaultItem__pb2
from WUProtos.Data import StaminaVaultItem_pb2 as WUProtos_dot_Data_dot_StaminaVaultItem__pb2
from WUProtos.Data import DarkDetectorVaultItem_pb2 as WUProtos_dot_Data_dot_DarkDetectorVaultItem__pb2
from WUProtos.Data import ContainerVaultItem_pb2 as WUProtos_dot_Data_dot_ContainerVaultItem__pb2
from WUProtos.Data import RunestoneVaultItem_pb2 as WUProtos_dot_Data_dot_RunestoneVaultItem__pb2
from WUProtos.Data.Potion import PotionVaultItem_pb2 as WUProtos_dot_Data_dot_Potion_dot_PotionVaultItem__pb2
from WUProtos.Data.Potion import PotionIngredientVaultItem_pb2 as WUProtos_dot_Data_dot_Potion_dot_PotionIngredientVaultItem__pb2
from WUProtos.Data import EnergyVaultItem_pb2 as WUProtos_dot_Data_dot_EnergyVaultItem__pb2
from WUProtos.Data import CauldronTimeItem_pb2 as WUProtos_dot_Data_dot_CauldronTimeItem__pb2
from WUProtos.Data import PotTimeItem_pb2 as WUProtos_dot_Data_dot_PotTimeItem__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/VaultItem.proto',
  package='WUProtos.Data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dWUProtos/Data/VaultItem.proto\x12\rWUProtos.Data\x1a%WUProtos/Data/CurrencyVaultItem.proto\x1a$WUProtos/Data/StaminaVaultItem.proto\x1a)WUProtos/Data/DarkDetectorVaultItem.proto\x1a&WUProtos/Data/ContainerVaultItem.proto\x1a&WUProtos/Data/RunestoneVaultItem.proto\x1a*WUProtos/Data/Potion/PotionVaultItem.proto\x1a\x34WUProtos/Data/Potion/PotionIngredientVaultItem.proto\x1a#WUProtos/Data/EnergyVaultItem.proto\x1a$WUProtos/Data/CauldronTimeItem.proto\x1a\x1fWUProtos/Data/PotTimeItem.proto\"\xd6\x06\n\tVaultItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x39\n\rcurrency_item\x18\x02 \x01(\x0b\x32 .WUProtos.Data.CurrencyVaultItemH\x00\x12\x37\n\x0cstamina_item\x18\x03 \x01(\x0b\x32\x1f.WUProtos.Data.StaminaVaultItemH\x00\x12=\n\rdetector_item\x18\x04 \x01(\x0b\x32$.WUProtos.Data.DarkDetectorVaultItemH\x00\x12;\n\x0e\x63ontainer_item\x18\x05 \x01(\x0b\x32!.WUProtos.Data.ContainerVaultItemH\x00\x12;\n\x0erunestone_item\x18\x06 \x01(\x0b\x32!.WUProtos.Data.RunestoneVaultItemH\x00\x12<\n\x0bpotion_item\x18\x07 \x01(\x0b\x32%.WUProtos.Data.Potion.PotionVaultItemH\x00\x12L\n\x11potion_ingredient\x18\x08 \x01(\x0b\x32/.WUProtos.Data.Potion.PotionIngredientVaultItemH\x00\x12\x35\n\x0b\x65nergy_item\x18\n \x01(\x0b\x32\x1e.WUProtos.Data.EnergyVaultItemH\x00\x12=\n\x12\x63\x61uldron_time_item\x18\x0b \x01(\x0b\x32\x1f.WUProtos.Data.CauldronTimeItemH\x00\x12\x33\n\rpot_time_item\x18\x0c \x01(\x0b\x32\x1a.WUProtos.Data.PotTimeItemH\x00\x12\x0b\n\x03\x63\x61p\x18\t \x01(\x03\x12\x16\n\x0erelative_value\x18\x64 \x01(\x05\x12\x1d\n\x15vault_category_gmt_id\x18\x65 \x01(\t\"\x83\x01\n\x0fPotionStateEnum\x12\n\n\x06usable\x10\x00\x12\x10\n\x0cmap_unusable\x10\x01\x12\x11\n\rpotion_active\x10\x02\x12\x13\n\x0fstronger_active\x10\x03\x12\x12\n\x0ehpalready_full\x10\x04\x12\x16\n\x12\x66ocus_already_full\x10\x05\x42\x0f\n\rVaultItemTypeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_CurrencyVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_StaminaVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_DarkDetectorVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_ContainerVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_RunestoneVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Potion_dot_PotionVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Potion_dot_PotionIngredientVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_EnergyVaultItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_CauldronTimeItem__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_PotTimeItem__pb2.DESCRIPTOR,])



_VAULTITEM_POTIONSTATEENUM = _descriptor.EnumDescriptor(
  name='PotionStateEnum',
  full_name='WUProtos.Data.VaultItem.PotionStateEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='usable', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='map_unusable', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='potion_active', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='stronger_active', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='hpalready_full', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='focus_already_full', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1161,
  serialized_end=1292,
)
_sym_db.RegisterEnumDescriptor(_VAULTITEM_POTIONSTATEENUM)


_VAULTITEM = _descriptor.Descriptor(
  name='VaultItem',
  full_name='WUProtos.Data.VaultItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='WUProtos.Data.VaultItem.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency_item', full_name='WUProtos.Data.VaultItem.currency_item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamina_item', full_name='WUProtos.Data.VaultItem.stamina_item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detector_item', full_name='WUProtos.Data.VaultItem.detector_item', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='container_item', full_name='WUProtos.Data.VaultItem.container_item', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runestone_item', full_name='WUProtos.Data.VaultItem.runestone_item', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='potion_item', full_name='WUProtos.Data.VaultItem.potion_item', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='potion_ingredient', full_name='WUProtos.Data.VaultItem.potion_ingredient', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='energy_item', full_name='WUProtos.Data.VaultItem.energy_item', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cauldron_time_item', full_name='WUProtos.Data.VaultItem.cauldron_time_item', index=9,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pot_time_item', full_name='WUProtos.Data.VaultItem.pot_time_item', index=10,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cap', full_name='WUProtos.Data.VaultItem.cap', index=11,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relative_value', full_name='WUProtos.Data.VaultItem.relative_value', index=12,
      number=100, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vault_category_gmt_id', full_name='WUProtos.Data.VaultItem.vault_category_gmt_id', index=13,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VAULTITEM_POTIONSTATEENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='VaultItemType', full_name='WUProtos.Data.VaultItem.VaultItemType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=455,
  serialized_end=1309,
)

_VAULTITEM.fields_by_name['currency_item'].message_type = WUProtos_dot_Data_dot_CurrencyVaultItem__pb2._CURRENCYVAULTITEM
_VAULTITEM.fields_by_name['stamina_item'].message_type = WUProtos_dot_Data_dot_StaminaVaultItem__pb2._STAMINAVAULTITEM
_VAULTITEM.fields_by_name['detector_item'].message_type = WUProtos_dot_Data_dot_DarkDetectorVaultItem__pb2._DARKDETECTORVAULTITEM
_VAULTITEM.fields_by_name['container_item'].message_type = WUProtos_dot_Data_dot_ContainerVaultItem__pb2._CONTAINERVAULTITEM
_VAULTITEM.fields_by_name['runestone_item'].message_type = WUProtos_dot_Data_dot_RunestoneVaultItem__pb2._RUNESTONEVAULTITEM
_VAULTITEM.fields_by_name['potion_item'].message_type = WUProtos_dot_Data_dot_Potion_dot_PotionVaultItem__pb2._POTIONVAULTITEM
_VAULTITEM.fields_by_name['potion_ingredient'].message_type = WUProtos_dot_Data_dot_Potion_dot_PotionIngredientVaultItem__pb2._POTIONINGREDIENTVAULTITEM
_VAULTITEM.fields_by_name['energy_item'].message_type = WUProtos_dot_Data_dot_EnergyVaultItem__pb2._ENERGYVAULTITEM
_VAULTITEM.fields_by_name['cauldron_time_item'].message_type = WUProtos_dot_Data_dot_CauldronTimeItem__pb2._CAULDRONTIMEITEM
_VAULTITEM.fields_by_name['pot_time_item'].message_type = WUProtos_dot_Data_dot_PotTimeItem__pb2._POTTIMEITEM
_VAULTITEM_POTIONSTATEENUM.containing_type = _VAULTITEM
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['currency_item'])
_VAULTITEM.fields_by_name['currency_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['stamina_item'])
_VAULTITEM.fields_by_name['stamina_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['detector_item'])
_VAULTITEM.fields_by_name['detector_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['container_item'])
_VAULTITEM.fields_by_name['container_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['runestone_item'])
_VAULTITEM.fields_by_name['runestone_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['potion_item'])
_VAULTITEM.fields_by_name['potion_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['potion_ingredient'])
_VAULTITEM.fields_by_name['potion_ingredient'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['energy_item'])
_VAULTITEM.fields_by_name['energy_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['cauldron_time_item'])
_VAULTITEM.fields_by_name['cauldron_time_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
_VAULTITEM.oneofs_by_name['VaultItemType'].fields.append(
  _VAULTITEM.fields_by_name['pot_time_item'])
_VAULTITEM.fields_by_name['pot_time_item'].containing_oneof = _VAULTITEM.oneofs_by_name['VaultItemType']
DESCRIPTOR.message_types_by_name['VaultItem'] = _VAULTITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VaultItem = _reflection.GeneratedProtocolMessageType('VaultItem', (_message.Message,), dict(
  DESCRIPTOR = _VAULTITEM,
  __module__ = 'WUProtos.Data.VaultItem_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.VaultItem)
  ))
_sym_db.RegisterMessage(VaultItem)


# @@protoc_insertion_point(module_scope)
