# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Collection/CollectionFamily.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Enums import CollectionFamilyType_pb2 as WUProtos_dot_Enums_dot_CollectionFamilyType__pb2
from WUProtos.Data.Collection import CollectionFamilyLevel_pb2 as WUProtos_dot_Data_dot_Collection_dot_CollectionFamilyLevel__pb2
from WUProtos.Data.Loot import LootCollection_pb2 as WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2
from WUProtos.Data import Requirements_pb2 as WUProtos_dot_Data_dot_Requirements__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Collection/CollectionFamily.proto',
  package='WUProtos.Data.Collection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/WUProtos/Data/Collection/CollectionFamily.proto\x12\x18WUProtos.Data.Collection\x1a)WUProtos/Enums/CollectionFamilyType.proto\x1a\x34WUProtos/Data/Collection/CollectionFamilyLevel.proto\x1a\'WUProtos/Data/Loot/LootCollection.proto\x1a WUProtos/Data/Requirements.proto\"\xb9\x04\n\x10\x43ollectionFamily\x12\n\n\x02id\x18\x01 \x01(\t\x12\x39\n\x0b\x66\x61mily_type\x18\x02 \x01(\x0e\x32$.WUProtos.Enums.CollectionFamilyType\x12\r\n\x05items\x18\x03 \x03(\t\x12?\n\x06levels\x18\x04 \x03(\x0b\x32/.WUProtos.Data.Collection.CollectionFamilyLevel\x12\r\n\x05pages\x18\x05 \x03(\t\x12\x18\n\x10\x66\x61mily_rune_name\x18\x06 \x01(\t\x12\x1c\n\x14\x66\x61mily_rank_table_id\x18\x07 \x01(\t\x12<\n\x10returned_rewards\x18\x08 \x03(\x0b\x32\".WUProtos.Data.Loot.LootCollection\x12\x0f\n\x07rune_id\x18\t \x03(\t\x12\x12\n\napex_items\x18\n \x03(\t\x12\x38\n\x13unlock_requirements\x18\x0b \x01(\x0b\x32\x1b.WUProtos.Data.Requirements\x12R\n\x0fsubfeature_type\x18\x0c \x01(\x0e\x32\x39.WUProtos.Data.Collection.CollectionFamily.SubfeatureType\"V\n\x0eSubfeatureType\x12\t\n\x05UNSET\x10\x00\x12\x0f\n\x0b\x45XPLORATION\x10\x01\x12\r\n\tCHALLENGE\x10\x02\x12\r\n\tMYSTERIES\x10\x03\x12\n\n\x06\x45VENTS\x10\x04\x62\x06proto3')
  ,
  dependencies=[WUProtos_dot_Enums_dot_CollectionFamilyType__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Collection_dot_CollectionFamilyLevel__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Requirements__pb2.DESCRIPTOR,])



_COLLECTIONFAMILY_SUBFEATURETYPE = _descriptor.EnumDescriptor(
  name='SubfeatureType',
  full_name='WUProtos.Data.Collection.CollectionFamily.SubfeatureType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPLORATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHALLENGE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MYSTERIES', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENTS', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=733,
  serialized_end=819,
)
_sym_db.RegisterEnumDescriptor(_COLLECTIONFAMILY_SUBFEATURETYPE)


_COLLECTIONFAMILY = _descriptor.Descriptor(
  name='CollectionFamily',
  full_name='WUProtos.Data.Collection.CollectionFamily',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='WUProtos.Data.Collection.CollectionFamily.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='family_type', full_name='WUProtos.Data.Collection.CollectionFamily.family_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='WUProtos.Data.Collection.CollectionFamily.items', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='levels', full_name='WUProtos.Data.Collection.CollectionFamily.levels', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pages', full_name='WUProtos.Data.Collection.CollectionFamily.pages', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='family_rune_name', full_name='WUProtos.Data.Collection.CollectionFamily.family_rune_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='family_rank_table_id', full_name='WUProtos.Data.Collection.CollectionFamily.family_rank_table_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returned_rewards', full_name='WUProtos.Data.Collection.CollectionFamily.returned_rewards', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rune_id', full_name='WUProtos.Data.Collection.CollectionFamily.rune_id', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apex_items', full_name='WUProtos.Data.Collection.CollectionFamily.apex_items', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unlock_requirements', full_name='WUProtos.Data.Collection.CollectionFamily.unlock_requirements', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subfeature_type', full_name='WUProtos.Data.Collection.CollectionFamily.subfeature_type', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COLLECTIONFAMILY_SUBFEATURETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=819,
)

_COLLECTIONFAMILY.fields_by_name['family_type'].enum_type = WUProtos_dot_Enums_dot_CollectionFamilyType__pb2._COLLECTIONFAMILYTYPE
_COLLECTIONFAMILY.fields_by_name['levels'].message_type = WUProtos_dot_Data_dot_Collection_dot_CollectionFamilyLevel__pb2._COLLECTIONFAMILYLEVEL
_COLLECTIONFAMILY.fields_by_name['returned_rewards'].message_type = WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2._LOOTCOLLECTION
_COLLECTIONFAMILY.fields_by_name['unlock_requirements'].message_type = WUProtos_dot_Data_dot_Requirements__pb2._REQUIREMENTS
_COLLECTIONFAMILY.fields_by_name['subfeature_type'].enum_type = _COLLECTIONFAMILY_SUBFEATURETYPE
_COLLECTIONFAMILY_SUBFEATURETYPE.containing_type = _COLLECTIONFAMILY
DESCRIPTOR.message_types_by_name['CollectionFamily'] = _COLLECTIONFAMILY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CollectionFamily = _reflection.GeneratedProtocolMessageType('CollectionFamily', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTIONFAMILY,
  __module__ = 'WUProtos.Data.Collection.CollectionFamily_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Collection.CollectionFamily)
  ))
_sym_db.RegisterMessage(CollectionFamily)


# @@protoc_insertion_point(module_scope)
