# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Collection/CollectionFamilyRankTable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Collection import CollectionFamilyRank_pb2 as WUProtos_dot_Data_dot_Collection_dot_CollectionFamilyRank__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Collection/CollectionFamilyRankTable.proto',
  package='WUProtos.Data.Collection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n8WUProtos/Data/Collection/CollectionFamilyRankTable.proto\x12\x18WUProtos.Data.Collection\x1a\x33WUProtos/Data/Collection/CollectionFamilyRank.proto\"j\n\x19\x43ollectionFamilyRankTable\x12\n\n\x02id\x18\x01 \x01(\t\x12\x41\n\trank_data\x18\x02 \x03(\x0b\x32..WUProtos.Data.Collection.CollectionFamilyRankb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Collection_dot_CollectionFamilyRank__pb2.DESCRIPTOR,])




_COLLECTIONFAMILYRANKTABLE = _descriptor.Descriptor(
  name='CollectionFamilyRankTable',
  full_name='WUProtos.Data.Collection.CollectionFamilyRankTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='WUProtos.Data.Collection.CollectionFamilyRankTable.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank_data', full_name='WUProtos.Data.Collection.CollectionFamilyRankTable.rank_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=245,
)

_COLLECTIONFAMILYRANKTABLE.fields_by_name['rank_data'].message_type = WUProtos_dot_Data_dot_Collection_dot_CollectionFamilyRank__pb2._COLLECTIONFAMILYRANK
DESCRIPTOR.message_types_by_name['CollectionFamilyRankTable'] = _COLLECTIONFAMILYRANKTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CollectionFamilyRankTable = _reflection.GeneratedProtocolMessageType('CollectionFamilyRankTable', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTIONFAMILYRANKTABLE,
  __module__ = 'WUProtos.Data.Collection.CollectionFamilyRankTable_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Collection.CollectionFamilyRankTable)
  ))
_sym_db.RegisterMessage(CollectionFamilyRankTable)


# @@protoc_insertion_point(module_scope)
