# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Collection/CollectionFamilyLevel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Loot import LootCollection_pb2 as WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Collection/CollectionFamilyLevel.proto',
  package='WUProtos.Data.Collection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n4WUProtos/Data/Collection/CollectionFamilyLevel.proto\x12\x18WUProtos.Data.Collection\x1a\'WUProtos/Data/Loot/LootCollection.proto\"\xb3\x01\n\x15\x43ollectionFamilyLevel\x12\n\n\x02xp\x18\x01 \x01(\x03\x12<\n\x10returned_rewards\x18\x02 \x03(\x0b\x32\".WUProtos.Data.Loot.LootCollection\x12<\n\x10one_time_rewards\x18\x03 \x01(\x0b\x32\".WUProtos.Data.Loot.LootCollection\x12\x12\n\nlevel_desc\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2.DESCRIPTOR,])




_COLLECTIONFAMILYLEVEL = _descriptor.Descriptor(
  name='CollectionFamilyLevel',
  full_name='WUProtos.Data.Collection.CollectionFamilyLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xp', full_name='WUProtos.Data.Collection.CollectionFamilyLevel.xp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returned_rewards', full_name='WUProtos.Data.Collection.CollectionFamilyLevel.returned_rewards', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='one_time_rewards', full_name='WUProtos.Data.Collection.CollectionFamilyLevel.one_time_rewards', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level_desc', full_name='WUProtos.Data.Collection.CollectionFamilyLevel.level_desc', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=303,
)

_COLLECTIONFAMILYLEVEL.fields_by_name['returned_rewards'].message_type = WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2._LOOTCOLLECTION
_COLLECTIONFAMILYLEVEL.fields_by_name['one_time_rewards'].message_type = WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2._LOOTCOLLECTION
DESCRIPTOR.message_types_by_name['CollectionFamilyLevel'] = _COLLECTIONFAMILYLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CollectionFamilyLevel = _reflection.GeneratedProtocolMessageType('CollectionFamilyLevel', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTIONFAMILYLEVEL,
  __module__ = 'WUProtos.Data.Collection.CollectionFamilyLevel_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Collection.CollectionFamilyLevel)
  ))
_sym_db.RegisterMessage(CollectionFamilyLevel)


# @@protoc_insertion_point(module_scope)
