# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Responses/ContributeFlooPowderToFortressResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data import FlooNetworkFortressStatistics_pb2 as WUProtos_dot_Data_dot_FlooNetworkFortressStatistics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Responses/ContributeFlooPowderToFortressResponse.proto',
  package='WUProtos.Networking.Responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nJWUProtos/Networking/Responses/ContributeFlooPowderToFortressResponse.proto\x12\x1dWUProtos.Networking.Responses\x1a\x31WUProtos/Data/FlooNetworkFortressStatistics.proto\"\xfc\x02\n&ContributeFlooPowderToFortressResponse\x12\\\n\x06result\x18\x01 \x01(\x0e\x32L.WUProtos.Networking.Responses.ContributeFlooPowderToFortressResponse.Result\x12I\n\x13\x66ortress_statistics\x18\x02 \x01(\x0b\x32,.WUProtos.Data.FlooNetworkFortressStatistics\"\xa8\x01\n\x06Result\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x16\n\x12PLAYER_HAS_NO_TEAM\x10\x02\x12\x1c\n\x18INSUFFICIENT_FLOO_POWDER\x10\x03\x12\x19\n\x15TOO_FAR_FROM_FORTRESS\x10\x04\x12\x15\n\x11SEASON_NOT_ACTIVE\x10\x05\x12\x1c\n\x18\x46LOO_NETWORK_UNAVAILABLE\x10\x06\x62\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_FlooNetworkFortressStatistics__pb2.DESCRIPTOR,])



_CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='WUProtos.Networking.Responses.ContributeFlooPowderToFortressResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_HAS_NO_TEAM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSUFFICIENT_FLOO_POWDER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOO_FAR_FROM_FORTRESS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEASON_NOT_ACTIVE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOO_NETWORK_UNAVAILABLE', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=373,
  serialized_end=541,
)
_sym_db.RegisterEnumDescriptor(_CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE_RESULT)


_CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE = _descriptor.Descriptor(
  name='ContributeFlooPowderToFortressResponse',
  full_name='WUProtos.Networking.Responses.ContributeFlooPowderToFortressResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='WUProtos.Networking.Responses.ContributeFlooPowderToFortressResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fortress_statistics', full_name='WUProtos.Networking.Responses.ContributeFlooPowderToFortressResponse.fortress_statistics', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=541,
)

_CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE.fields_by_name['result'].enum_type = _CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE_RESULT
_CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE.fields_by_name['fortress_statistics'].message_type = WUProtos_dot_Data_dot_FlooNetworkFortressStatistics__pb2._FLOONETWORKFORTRESSSTATISTICS
_CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE_RESULT.containing_type = _CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE
DESCRIPTOR.message_types_by_name['ContributeFlooPowderToFortressResponse'] = _CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContributeFlooPowderToFortressResponse = _reflection.GeneratedProtocolMessageType('ContributeFlooPowderToFortressResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONTRIBUTEFLOOPOWDERTOFORTRESSRESPONSE,
  __module__ = 'WUProtos.Networking.Responses.ContributeFlooPowderToFortressResponse_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Responses.ContributeFlooPowderToFortressResponse)
  ))
_sym_db.RegisterMessage(ContributeFlooPowderToFortressResponse)


# @@protoc_insertion_point(module_scope)
