# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Responses/ContainerConsumptionResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Loot import LootCollection_pb2 as WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Responses/ContainerConsumptionResponse.proto',
  package='WUProtos.Networking.Responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n@WUProtos/Networking/Responses/ContainerConsumptionResponse.proto\x12\x1dWUProtos.Networking.Responses\x1a\'WUProtos/Data/Loot/LootCollection.proto\"\x99\x02\n\x1c\x43ontainerConsumptionResponse\x12R\n\x06status\x18\x01 \x01(\x0e\x32\x42.WUProtos.Networking.Responses.ContainerConsumptionResponse.Status\x12>\n\x12\x63ontainer_contents\x18\x02 \x01(\x0b\x32\".WUProtos.Data.Loot.LootCollection\"e\n\x06Status\x12\x08\n\x04NONE\x10\x00\x12(\n$UNKNOWN_CONTAINER_CONSUMPTION_RESULT\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\x1a\n\x16\x43ONTAINER_NOT_IN_VAULT\x10\x03\x62\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2.DESCRIPTOR,])



_CONTAINERCONSUMPTIONRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='WUProtos.Networking.Responses.ContainerConsumptionResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_CONTAINER_CONSUMPTION_RESULT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTAINER_NOT_IN_VAULT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=321,
  serialized_end=422,
)
_sym_db.RegisterEnumDescriptor(_CONTAINERCONSUMPTIONRESPONSE_STATUS)


_CONTAINERCONSUMPTIONRESPONSE = _descriptor.Descriptor(
  name='ContainerConsumptionResponse',
  full_name='WUProtos.Networking.Responses.ContainerConsumptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='WUProtos.Networking.Responses.ContainerConsumptionResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='container_contents', full_name='WUProtos.Networking.Responses.ContainerConsumptionResponse.container_contents', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTAINERCONSUMPTIONRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=422,
)

_CONTAINERCONSUMPTIONRESPONSE.fields_by_name['status'].enum_type = _CONTAINERCONSUMPTIONRESPONSE_STATUS
_CONTAINERCONSUMPTIONRESPONSE.fields_by_name['container_contents'].message_type = WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2._LOOTCOLLECTION
_CONTAINERCONSUMPTIONRESPONSE_STATUS.containing_type = _CONTAINERCONSUMPTIONRESPONSE
DESCRIPTOR.message_types_by_name['ContainerConsumptionResponse'] = _CONTAINERCONSUMPTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContainerConsumptionResponse = _reflection.GeneratedProtocolMessageType('ContainerConsumptionResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERCONSUMPTIONRESPONSE,
  __module__ = 'WUProtos.Networking.Responses.ContainerConsumptionResponse_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Responses.ContainerConsumptionResponse)
  ))
_sym_db.RegisterMessage(ContainerConsumptionResponse)


# @@protoc_insertion_point(module_scope)
