# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/responses/dbg_start_encounter_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wuprotos.networking.responses import encounter_start_response_pb2 as wuprotos_dot_networking_dot_responses_dot_encounter__start__response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/responses/dbg_start_encounter_response.proto',
  package='wuprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n@wuprotos/networking/responses/dbg_start_encounter_response.proto\x12\x1dwuprotos.networking.responses\x1a<wuprotos/networking/responses/encounter_start_response.proto\"d\n\x19\x44\x62gStartEncounterResponse\x12G\n\x08response\x18\x01 \x01(\x0b\x32\x35.wuprotos.networking.responses.EncounterStartResponseb\x06proto3')
  ,
  dependencies=[wuprotos_dot_networking_dot_responses_dot_encounter__start__response__pb2.DESCRIPTOR,])




_DBGSTARTENCOUNTERRESPONSE = _descriptor.Descriptor(
  name='DbgStartEncounterResponse',
  full_name='wuprotos.networking.responses.DbgStartEncounterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='wuprotos.networking.responses.DbgStartEncounterResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=261,
)

_DBGSTARTENCOUNTERRESPONSE.fields_by_name['response'].message_type = wuprotos_dot_networking_dot_responses_dot_encounter__start__response__pb2._ENCOUNTERSTARTRESPONSE
DESCRIPTOR.message_types_by_name['DbgStartEncounterResponse'] = _DBGSTARTENCOUNTERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbgStartEncounterResponse = _reflection.GeneratedProtocolMessageType('DbgStartEncounterResponse', (_message.Message,), dict(
  DESCRIPTOR = _DBGSTARTENCOUNTERRESPONSE,
  __module__ = 'wuprotos.networking.responses.dbg_start_encounter_response_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.responses.DbgStartEncounterResponse)
  ))
_sym_db.RegisterMessage(DbgStartEncounterResponse)


# @@protoc_insertion_point(module_scope)
