# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Responses/DbgChallengeWinResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Responses/DbgChallengeWinResponse.proto',
  package='WUProtos.Networking.Responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n;WUProtos/Networking/Responses/DbgChallengeWinResponse.proto\x12\x1dWUProtos.Networking.Responses\"\x19\n\x17\x44\x62gChallengeWinResponseb\x06proto3')
)




_DBGCHALLENGEWINRESPONSE = _descriptor.Descriptor(
  name='DbgChallengeWinResponse',
  full_name='WUProtos.Networking.Responses.DbgChallengeWinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['DbgChallengeWinResponse'] = _DBGCHALLENGEWINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbgChallengeWinResponse = _reflection.GeneratedProtocolMessageType('DbgChallengeWinResponse', (_message.Message,), dict(
  DESCRIPTOR = _DBGCHALLENGEWINRESPONSE,
  __module__ = 'WUProtos.Networking.Responses.DbgChallengeWinResponse_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Responses.DbgChallengeWinResponse)
  ))
_sym_db.RegisterMessage(DbgChallengeWinResponse)


# @@protoc_insertion_point(module_scope)
