# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/responses/get_store_pack_info_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wuprotos.data import store_pack_pb2 as wuprotos_dot_data_dot_store__pack__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/responses/get_store_pack_info_response.proto',
  package='wuprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n@wuprotos/networking/responses/get_store_pack_info_response.proto\x12\x1dwuprotos.networking.responses\x1a\x1ewuprotos/data/store_pack.proto\"\xc7\x01\n\x18GetStorePackInfoResponse\x12,\n\nstore_pack\x18\x01 \x01(\x0b\x32\x18.wuprotos.data.StorePack\x12N\n\x06status\x18\x02 \x01(\x0e\x32>.wuprotos.networking.responses.GetStorePackInfoResponse.Status\"-\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')
  ,
  dependencies=[wuprotos_dot_data_dot_store__pack__pb2.DESCRIPTOR,])



_GETSTOREPACKINFORESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='wuprotos.networking.responses.GetStorePackInfoResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=286,
  serialized_end=331,
)
_sym_db.RegisterEnumDescriptor(_GETSTOREPACKINFORESPONSE_STATUS)


_GETSTOREPACKINFORESPONSE = _descriptor.Descriptor(
  name='GetStorePackInfoResponse',
  full_name='wuprotos.networking.responses.GetStorePackInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='store_pack', full_name='wuprotos.networking.responses.GetStorePackInfoResponse.store_pack', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='wuprotos.networking.responses.GetStorePackInfoResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETSTOREPACKINFORESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=331,
)

_GETSTOREPACKINFORESPONSE.fields_by_name['store_pack'].message_type = wuprotos_dot_data_dot_store__pack__pb2._STOREPACK
_GETSTOREPACKINFORESPONSE.fields_by_name['status'].enum_type = _GETSTOREPACKINFORESPONSE_STATUS
_GETSTOREPACKINFORESPONSE_STATUS.containing_type = _GETSTOREPACKINFORESPONSE
DESCRIPTOR.message_types_by_name['GetStorePackInfoResponse'] = _GETSTOREPACKINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStorePackInfoResponse = _reflection.GeneratedProtocolMessageType('GetStorePackInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSTOREPACKINFORESPONSE,
  __module__ = 'wuprotos.networking.responses.get_store_pack_info_response_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.responses.GetStorePackInfoResponse)
  ))
_sym_db.RegisterMessage(GetStorePackInfoResponse)


# @@protoc_insertion_point(module_scope)
