# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/responses/instant_finish_brewing_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/responses/instant_finish_brewing_response.proto',
  package='wuprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nCwuprotos/networking/responses/instant_finish_brewing_response.proto\x12\x1dwuprotos.networking.responses\"\xf7\x01\n\x1cInstantFinishBrewingResponse\x12\x66\n\x06result\x18\x01 \x01(\x0e\x32V.wuprotos.networking.responses.InstantFinishBrewingResponse.InstantFinishBrewingResult\"o\n\x1aInstantFinishBrewingResult\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x1a\n\x16INSUFFICIENT_RESOURCES\x10\x02\x12\x1b\n\x17\x45MPTY_CAULDRON_SELECTED\x10\x03\x62\x06proto3')
)



_INSTANTFINISHBREWINGRESPONSE_INSTANTFINISHBREWINGRESULT = _descriptor.EnumDescriptor(
  name='InstantFinishBrewingResult',
  full_name='wuprotos.networking.responses.InstantFinishBrewingResponse.InstantFinishBrewingResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSUFFICIENT_RESOURCES', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMPTY_CAULDRON_SELECTED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=239,
  serialized_end=350,
)
_sym_db.RegisterEnumDescriptor(_INSTANTFINISHBREWINGRESPONSE_INSTANTFINISHBREWINGRESULT)


_INSTANTFINISHBREWINGRESPONSE = _descriptor.Descriptor(
  name='InstantFinishBrewingResponse',
  full_name='wuprotos.networking.responses.InstantFinishBrewingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='wuprotos.networking.responses.InstantFinishBrewingResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSTANTFINISHBREWINGRESPONSE_INSTANTFINISHBREWINGRESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=350,
)

_INSTANTFINISHBREWINGRESPONSE.fields_by_name['result'].enum_type = _INSTANTFINISHBREWINGRESPONSE_INSTANTFINISHBREWINGRESULT
_INSTANTFINISHBREWINGRESPONSE_INSTANTFINISHBREWINGRESULT.containing_type = _INSTANTFINISHBREWINGRESPONSE
DESCRIPTOR.message_types_by_name['InstantFinishBrewingResponse'] = _INSTANTFINISHBREWINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstantFinishBrewingResponse = _reflection.GeneratedProtocolMessageType('InstantFinishBrewingResponse', (_message.Message,), dict(
  DESCRIPTOR = _INSTANTFINISHBREWINGRESPONSE,
  __module__ = 'wuprotos.networking.responses.instant_finish_brewing_response_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.responses.InstantFinishBrewingResponse)
  ))
_sym_db.RegisterMessage(InstantFinishBrewingResponse)


# @@protoc_insertion_point(module_scope)
