# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Responses/JoinChamberResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Enums import ChallengeRpcStatus_pb2 as WUProtos_dot_Enums_dot_ChallengeRpcStatus__pb2
from WUProtos.Data import ChamberState_pb2 as WUProtos_dot_Data_dot_ChamberState__pb2
from WUProtos.Data.Client import ClientPlayerSnapshot_pb2 as WUProtos_dot_Data_dot_Client_dot_ClientPlayerSnapshot__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Responses/JoinChamberResponse.proto',
  package='WUProtos.Networking.Responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n7WUProtos/Networking/Responses/JoinChamberResponse.proto\x12\x1dWUProtos.Networking.Responses\x1a\'WUProtos/Enums/ChallengeRpcStatus.proto\x1a WUProtos/Data/ChamberState.proto\x1a/WUProtos/Data/Client/ClientPlayerSnapshot.proto\"\xf1\x01\n\x13JoinChamberResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".WUProtos.Enums.ChallengeRpcStatus\x12*\n\x05state\x18\x02 \x01(\x0b\x32\x1b.WUProtos.Data.ChamberState\x12\x43\n\x0fplayer_snapshot\x18\x03 \x01(\x0b\x32*.WUProtos.Data.Client.ClientPlayerSnapshot\x12\x12\n\npartner_id\x18\x04 \x01(\t\x12!\n\x19\x66ortress_cooldown_left_ms\x18\x05 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[WUProtos_dot_Enums_dot_ChallengeRpcStatus__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_ChamberState__pb2.DESCRIPTOR,WUProtos_dot_Data_dot_Client_dot_ClientPlayerSnapshot__pb2.DESCRIPTOR,])




_JOINCHAMBERRESPONSE = _descriptor.Descriptor(
  name='JoinChamberResponse',
  full_name='WUProtos.Networking.Responses.JoinChamberResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='WUProtos.Networking.Responses.JoinChamberResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='WUProtos.Networking.Responses.JoinChamberResponse.state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_snapshot', full_name='WUProtos.Networking.Responses.JoinChamberResponse.player_snapshot', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partner_id', full_name='WUProtos.Networking.Responses.JoinChamberResponse.partner_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fortress_cooldown_left_ms', full_name='WUProtos.Networking.Responses.JoinChamberResponse.fortress_cooldown_left_ms', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=456,
)

_JOINCHAMBERRESPONSE.fields_by_name['status'].enum_type = WUProtos_dot_Enums_dot_ChallengeRpcStatus__pb2._CHALLENGERPCSTATUS
_JOINCHAMBERRESPONSE.fields_by_name['state'].message_type = WUProtos_dot_Data_dot_ChamberState__pb2._CHAMBERSTATE
_JOINCHAMBERRESPONSE.fields_by_name['player_snapshot'].message_type = WUProtos_dot_Data_dot_Client_dot_ClientPlayerSnapshot__pb2._CLIENTPLAYERSNAPSHOT
DESCRIPTOR.message_types_by_name['JoinChamberResponse'] = _JOINCHAMBERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoinChamberResponse = _reflection.GeneratedProtocolMessageType('JoinChamberResponse', (_message.Message,), dict(
  DESCRIPTOR = _JOINCHAMBERRESPONSE,
  __module__ = 'WUProtos.Networking.Responses.JoinChamberResponse_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Responses.JoinChamberResponse)
  ))
_sym_db.RegisterMessage(JoinChamberResponse)


# @@protoc_insertion_point(module_scope)
