# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Responses/LootOutpostResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Loot import LootCollection_pb2 as WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Responses/LootOutpostResponse.proto',
  package='WUProtos.Networking.Responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n7WUProtos/Networking/Responses/LootOutpostResponse.proto\x12\x1dWUProtos.Networking.Responses\x1a\'WUProtos/Data/Loot/LootCollection.proto\"\xb5\x02\n\x13LootOutpostResponse\x12I\n\x06status\x18\x01 \x01(\x0e\x32\x39.WUProtos.Networking.Responses.LootOutpostResponse.Status\x12\x18\n\x10\x61warded_food_key\x18\x02 \x01(\x03\x12\x16\n\x0enext_loot_time\x18\x03 \x01(\x03\x12\x30\n\x04loot\x18\x04 \x01(\x0b\x32\".WUProtos.Data.Loot.LootCollection\x12\x12\n\npartner_id\x18\x05 \x01(\t\"[\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07TOO_FAR\x10\x02\x12\x0f\n\x0bON_COOLDOWN\x10\x03\x12\x0b\n\x07SUCCESS\x10\x04\x12\x0e\n\nPOI_CLOSED\x10\x05\x62\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2.DESCRIPTOR,])



_LOOTOUTPOSTRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='WUProtos.Networking.Responses.LootOutpostResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOO_FAR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON_COOLDOWN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_CLOSED', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=350,
  serialized_end=441,
)
_sym_db.RegisterEnumDescriptor(_LOOTOUTPOSTRESPONSE_STATUS)


_LOOTOUTPOSTRESPONSE = _descriptor.Descriptor(
  name='LootOutpostResponse',
  full_name='WUProtos.Networking.Responses.LootOutpostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='WUProtos.Networking.Responses.LootOutpostResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='awarded_food_key', full_name='WUProtos.Networking.Responses.LootOutpostResponse.awarded_food_key', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_loot_time', full_name='WUProtos.Networking.Responses.LootOutpostResponse.next_loot_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loot', full_name='WUProtos.Networking.Responses.LootOutpostResponse.loot', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partner_id', full_name='WUProtos.Networking.Responses.LootOutpostResponse.partner_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOOTOUTPOSTRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=441,
)

_LOOTOUTPOSTRESPONSE.fields_by_name['status'].enum_type = _LOOTOUTPOSTRESPONSE_STATUS
_LOOTOUTPOSTRESPONSE.fields_by_name['loot'].message_type = WUProtos_dot_Data_dot_Loot_dot_LootCollection__pb2._LOOTCOLLECTION
_LOOTOUTPOSTRESPONSE_STATUS.containing_type = _LOOTOUTPOSTRESPONSE
DESCRIPTOR.message_types_by_name['LootOutpostResponse'] = _LOOTOUTPOSTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LootOutpostResponse = _reflection.GeneratedProtocolMessageType('LootOutpostResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOOTOUTPOSTRESPONSE,
  __module__ = 'WUProtos.Networking.Responses.LootOutpostResponse_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Responses.LootOutpostResponse)
  ))
_sym_db.RegisterMessage(LootOutpostResponse)


# @@protoc_insertion_point(module_scope)
