# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Responses/NotifyPrivacyPolicyResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Responses/NotifyPrivacyPolicyResponse.proto',
  package='WUProtos.Networking.Responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n?WUProtos/Networking/Responses/NotifyPrivacyPolicyResponse.proto\x12\x1dWUProtos.Networking.Responses\"\xa3\x01\n\x1bNotifyPrivacyPolicyResponse\x12Q\n\x06status\x18\x01 \x01(\x0e\x32\x41.WUProtos.Networking.Responses.NotifyPrivacyPolicyResponse.Status\"1\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x62\x06proto3')
)



_NOTIFYPRIVACYPOLICYRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='WUProtos.Networking.Responses.NotifyPrivacyPolicyResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=213,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_NOTIFYPRIVACYPOLICYRESPONSE_STATUS)


_NOTIFYPRIVACYPOLICYRESPONSE = _descriptor.Descriptor(
  name='NotifyPrivacyPolicyResponse',
  full_name='WUProtos.Networking.Responses.NotifyPrivacyPolicyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='WUProtos.Networking.Responses.NotifyPrivacyPolicyResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NOTIFYPRIVACYPOLICYRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=262,
)

_NOTIFYPRIVACYPOLICYRESPONSE.fields_by_name['status'].enum_type = _NOTIFYPRIVACYPOLICYRESPONSE_STATUS
_NOTIFYPRIVACYPOLICYRESPONSE_STATUS.containing_type = _NOTIFYPRIVACYPOLICYRESPONSE
DESCRIPTOR.message_types_by_name['NotifyPrivacyPolicyResponse'] = _NOTIFYPRIVACYPOLICYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotifyPrivacyPolicyResponse = _reflection.GeneratedProtocolMessageType('NotifyPrivacyPolicyResponse', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYPRIVACYPOLICYRESPONSE,
  __module__ = 'WUProtos.Networking.Responses.NotifyPrivacyPolicyResponse_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Responses.NotifyPrivacyPolicyResponse)
  ))
_sym_db.RegisterMessage(NotifyPrivacyPolicyResponse)


# @@protoc_insertion_point(module_scope)
