# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/responses/redeem_poi_pass_code_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wuprotos.data.loot import loot_reward_pb2 as wuprotos_dot_data_dot_loot_dot_loot__reward__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/responses/redeem_poi_pass_code_response.proto',
  package='wuprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nAwuprotos/networking/responses/redeem_poi_pass_code_response.proto\x12\x1dwuprotos.networking.responses\x1a$wuprotos/data/loot/loot_reward.proto\"\xc8\x02\n\x19RedeemPoiPassCodeResponse\x12O\n\x06status\x18\x01 \x01(\x0e\x32?.wuprotos.networking.responses.RedeemPoiPassCodeResponse.Status\x12>\n\x07rewards\x18\x02 \x01(\x0b\x32-.wuprotos.data.loot.LootReward.LootCollection\"\x99\x01\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x14\n\x10\x41LREADY_REDEEMED\x10\x02\x12\x1a\n\x16\x46\x41ILED_INVENTORY_CHECK\x10\x03\x12\x10\n\x0cOUT_OF_RANGE\x10\x04\x12\x12\n\x0eWRONG_LOCATION\x10\x05\x12\x10\n\x0cRATE_LIMITED\x10\x06\x12\x0b\n\x07INVALID\x10\x07\x62\x06proto3')
  ,
  dependencies=[wuprotos_dot_data_dot_loot_dot_loot__reward__pb2.DESCRIPTOR,])



_REDEEMPOIPASSCODERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='wuprotos.networking.responses.RedeemPoiPassCodeResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_REDEEMED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED_INVENTORY_CHECK', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUT_OF_RANGE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRONG_LOCATION', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RATE_LIMITED', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=314,
  serialized_end=467,
)
_sym_db.RegisterEnumDescriptor(_REDEEMPOIPASSCODERESPONSE_STATUS)


_REDEEMPOIPASSCODERESPONSE = _descriptor.Descriptor(
  name='RedeemPoiPassCodeResponse',
  full_name='wuprotos.networking.responses.RedeemPoiPassCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='wuprotos.networking.responses.RedeemPoiPassCodeResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rewards', full_name='wuprotos.networking.responses.RedeemPoiPassCodeResponse.rewards', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REDEEMPOIPASSCODERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=467,
)

_REDEEMPOIPASSCODERESPONSE.fields_by_name['status'].enum_type = _REDEEMPOIPASSCODERESPONSE_STATUS
_REDEEMPOIPASSCODERESPONSE.fields_by_name['rewards'].message_type = wuprotos_dot_data_dot_loot_dot_loot__reward__pb2._LOOTREWARD_LOOTCOLLECTION
_REDEEMPOIPASSCODERESPONSE_STATUS.containing_type = _REDEEMPOIPASSCODERESPONSE
DESCRIPTOR.message_types_by_name['RedeemPoiPassCodeResponse'] = _REDEEMPOIPASSCODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RedeemPoiPassCodeResponse = _reflection.GeneratedProtocolMessageType('RedeemPoiPassCodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _REDEEMPOIPASSCODERESPONSE,
  __module__ = 'wuprotos.networking.responses.redeem_poi_pass_code_response_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.responses.RedeemPoiPassCodeResponse)
  ))
_sym_db.RegisterMessage(RedeemPoiPassCodeResponse)


# @@protoc_insertion_point(module_scope)
