# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/responses/storyboard_complete_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/responses/storyboard_complete_response.proto',
  package='wuprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n@wuprotos/networking/responses/storyboard_complete_response.proto\x12\x1dwuprotos.networking.responses\"\xad\x02\n\x1aStoryboardCompleteResponse\x12P\n\x06status\x18\x01 \x01(\x0e\x32@.wuprotos.networking.responses.StoryboardCompleteResponse.Status\"\xbc\x01\n\x06Status\x12\x1f\n\x1bSTORYBOARD_COMPLETE_UNKNOWN\x10\x00\x12\x1f\n\x1bSTORYBOARD_COMPLETE_SUCCESS\x10\x01\x12)\n%STORYBOARD_COMPLETE_ALREADY_COMPLETED\x10\x02\x12&\n\"STORYBOARD_COMPLETE_STEPS_MISMATCH\x10\x03\x12\x1d\n\x19STORYBOARD_COMPLETE_ERROR\x10\x04\x62\x06proto3')
)



_STORYBOARDCOMPLETERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='wuprotos.networking.responses.StoryboardCompleteResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_COMPLETE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_COMPLETE_SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_COMPLETE_ALREADY_COMPLETED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_COMPLETE_STEPS_MISMATCH', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORYBOARD_COMPLETE_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=213,
  serialized_end=401,
)
_sym_db.RegisterEnumDescriptor(_STORYBOARDCOMPLETERESPONSE_STATUS)


_STORYBOARDCOMPLETERESPONSE = _descriptor.Descriptor(
  name='StoryboardCompleteResponse',
  full_name='wuprotos.networking.responses.StoryboardCompleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='wuprotos.networking.responses.StoryboardCompleteResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STORYBOARDCOMPLETERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=401,
)

_STORYBOARDCOMPLETERESPONSE.fields_by_name['status'].enum_type = _STORYBOARDCOMPLETERESPONSE_STATUS
_STORYBOARDCOMPLETERESPONSE_STATUS.containing_type = _STORYBOARDCOMPLETERESPONSE
DESCRIPTOR.message_types_by_name['StoryboardCompleteResponse'] = _STORYBOARDCOMPLETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoryboardCompleteResponse = _reflection.GeneratedProtocolMessageType('StoryboardCompleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _STORYBOARDCOMPLETERESPONSE,
  __module__ = 'wuprotos.networking.responses.storyboard_complete_response_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.responses.StoryboardCompleteResponse)
  ))
_sym_db.RegisterMessage(StoryboardCompleteResponse)


# @@protoc_insertion_point(module_scope)
