# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Profession/ProfessionActiveBuffSource.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Profession/ProfessionActiveBuffSource.proto',
  package='WUProtos.Data.Profession',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n9WUProtos/Data/Profession/ProfessionActiveBuffSource.proto\x12\x18WUProtos.Data.Profession\"v\n\x1aProfessionActiveBuffSource\x12\x19\n\x11profession_gmt_id\x18\x01 \x01(\t\x12\x1e\n\x16profession_gmt_node_id\x18\x02 \x01(\t\x12\x1d\n\x15profession_node_level\x18\x03 \x01(\rb\x06proto3')
)




_PROFESSIONACTIVEBUFFSOURCE = _descriptor.Descriptor(
  name='ProfessionActiveBuffSource',
  full_name='WUProtos.Data.Profession.ProfessionActiveBuffSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profession_gmt_id', full_name='WUProtos.Data.Profession.ProfessionActiveBuffSource.profession_gmt_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profession_gmt_node_id', full_name='WUProtos.Data.Profession.ProfessionActiveBuffSource.profession_gmt_node_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profession_node_level', full_name='WUProtos.Data.Profession.ProfessionActiveBuffSource.profession_node_level', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['ProfessionActiveBuffSource'] = _PROFESSIONACTIVEBUFFSOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProfessionActiveBuffSource = _reflection.GeneratedProtocolMessageType('ProfessionActiveBuffSource', (_message.Message,), dict(
  DESCRIPTOR = _PROFESSIONACTIVEBUFFSOURCE,
  __module__ = 'WUProtos.Data.Profession.ProfessionActiveBuffSource_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Profession.ProfessionActiveBuffSource)
  ))
_sym_db.RegisterMessage(ProfessionActiveBuffSource)


# @@protoc_insertion_point(module_scope)
