# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Requests/Messages/AcceptTermsOfServiceMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Requests/Messages/AcceptTermsOfServiceMessage.proto',
  package='WUProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nGWUProtos/Networking/Requests/Messages/AcceptTermsOfServiceMessage.proto\x12%WUProtos.Networking.Requests.Messages\"\x1d\n\x1b\x41\x63\x63\x65ptTermsOfServiceMessageb\x06proto3')
)




_ACCEPTTERMSOFSERVICEMESSAGE = _descriptor.Descriptor(
  name='AcceptTermsOfServiceMessage',
  full_name='WUProtos.Networking.Requests.Messages.AcceptTermsOfServiceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['AcceptTermsOfServiceMessage'] = _ACCEPTTERMSOFSERVICEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AcceptTermsOfServiceMessage = _reflection.GeneratedProtocolMessageType('AcceptTermsOfServiceMessage', (_message.Message,), dict(
  DESCRIPTOR = _ACCEPTTERMSOFSERVICEMESSAGE,
  __module__ = 'WUProtos.Networking.Requests.Messages.AcceptTermsOfServiceMessage_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Requests.Messages.AcceptTermsOfServiceMessage)
  ))
_sym_db.RegisterMessage(AcceptTermsOfServiceMessage)


# @@protoc_insertion_point(module_scope)
