# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Requests/Messages/AdminUpdateSkuMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data import SkuData_pb2 as WUProtos_dot_Data_dot_SkuData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Requests/Messages/AdminUpdateSkuMessage.proto',
  package='WUProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nAWUProtos/Networking/Requests/Messages/AdminUpdateSkuMessage.proto\x12%WUProtos.Networking.Requests.Messages\x1a\x1bWUProtos/Data/SkuData.proto\"A\n\x15\x41\x64minUpdateSkuMessage\x12(\n\x08sku_data\x18\x01 \x01(\x0b\x32\x16.WUProtos.Data.SkuDatab\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_SkuData__pb2.DESCRIPTOR,])




_ADMINUPDATESKUMESSAGE = _descriptor.Descriptor(
  name='AdminUpdateSkuMessage',
  full_name='WUProtos.Networking.Requests.Messages.AdminUpdateSkuMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sku_data', full_name='WUProtos.Networking.Requests.Messages.AdminUpdateSkuMessage.sku_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=202,
)

_ADMINUPDATESKUMESSAGE.fields_by_name['sku_data'].message_type = WUProtos_dot_Data_dot_SkuData__pb2._SKUDATA
DESCRIPTOR.message_types_by_name['AdminUpdateSkuMessage'] = _ADMINUPDATESKUMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdminUpdateSkuMessage = _reflection.GeneratedProtocolMessageType('AdminUpdateSkuMessage', (_message.Message,), dict(
  DESCRIPTOR = _ADMINUPDATESKUMESSAGE,
  __module__ = 'WUProtos.Networking.Requests.Messages.AdminUpdateSkuMessage_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Requests.Messages.AdminUpdateSkuMessage)
  ))
_sym_db.RegisterMessage(AdminUpdateSkuMessage)


# @@protoc_insertion_point(module_scope)
