# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/requests/messages/dbg_simulate_walking_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/requests/messages/dbg_simulate_walking_message.proto',
  package='wuprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nHwuprotos/networking/requests/messages/dbg_simulate_walking_message.proto\x12%wuprotos.networking.requests.messages\":\n\x19\x44\x62gSimulateWalkingMessage\x12\x1d\n\x15\x64istance_simulated_km\x18\x01 \x01(\x02\x62\x06proto3')
)




_DBGSIMULATEWALKINGMESSAGE = _descriptor.Descriptor(
  name='DbgSimulateWalkingMessage',
  full_name='wuprotos.networking.requests.messages.DbgSimulateWalkingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance_simulated_km', full_name='wuprotos.networking.requests.messages.DbgSimulateWalkingMessage.distance_simulated_km', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['DbgSimulateWalkingMessage'] = _DBGSIMULATEWALKINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbgSimulateWalkingMessage = _reflection.GeneratedProtocolMessageType('DbgSimulateWalkingMessage', (_message.Message,), dict(
  DESCRIPTOR = _DBGSIMULATEWALKINGMESSAGE,
  __module__ = 'wuprotos.networking.requests.messages.dbg_simulate_walking_message_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.requests.messages.DbgSimulateWalkingMessage)
  ))
_sym_db.RegisterMessage(DbgSimulateWalkingMessage)


# @@protoc_insertion_point(module_scope)
