# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/requests/messages/get_fortress_floo_network_statistics_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/requests/messages/get_fortress_floo_network_statistics_message.proto',
  package='wuprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nXwuprotos/networking/requests/messages/get_fortress_floo_network_statistics_message.proto\x12%wuprotos.networking.requests.messages\"c\n\'GetFortressFlooNetworkStatisticsMessage\x12\x13\n\x0b\x66ortress_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x62\x06proto3')
)




_GETFORTRESSFLOONETWORKSTATISTICSMESSAGE = _descriptor.Descriptor(
  name='GetFortressFlooNetworkStatisticsMessage',
  full_name='wuprotos.networking.requests.messages.GetFortressFlooNetworkStatisticsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fortress_id', full_name='wuprotos.networking.requests.messages.GetFortressFlooNetworkStatisticsMessage.fortress_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='wuprotos.networking.requests.messages.GetFortressFlooNetworkStatisticsMessage.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='wuprotos.networking.requests.messages.GetFortressFlooNetworkStatisticsMessage.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['GetFortressFlooNetworkStatisticsMessage'] = _GETFORTRESSFLOONETWORKSTATISTICSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFortressFlooNetworkStatisticsMessage = _reflection.GeneratedProtocolMessageType('GetFortressFlooNetworkStatisticsMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETFORTRESSFLOONETWORKSTATISTICSMESSAGE,
  __module__ = 'wuprotos.networking.requests.messages.get_fortress_floo_network_statistics_message_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.requests.messages.GetFortressFlooNetworkStatisticsMessage)
  ))
_sym_db.RegisterMessage(GetFortressFlooNetworkStatisticsMessage)


# @@protoc_insertion_point(module_scope)
