# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Requests/Messages/GetAllStorePacksMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Requests/Messages/GetAllStorePacksMessage.proto',
  package='WUProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nCWUProtos/Networking/Requests/Messages/GetAllStorePacksMessage.proto\x12%WUProtos.Networking.Requests.Messages\"\x19\n\x17GetAllStorePacksMessageb\x06proto3')
)




_GETALLSTOREPACKSMESSAGE = _descriptor.Descriptor(
  name='GetAllStorePacksMessage',
  full_name='WUProtos.Networking.Requests.Messages.GetAllStorePacksMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['GetAllStorePacksMessage'] = _GETALLSTOREPACKSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllStorePacksMessage = _reflection.GeneratedProtocolMessageType('GetAllStorePacksMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETALLSTOREPACKSMESSAGE,
  __module__ = 'WUProtos.Networking.Requests.Messages.GetAllStorePacksMessage_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Requests.Messages.GetAllStorePacksMessage)
  ))
_sym_db.RegisterMessage(GetAllStorePacksMessage)


# @@protoc_insertion_point(module_scope)
