# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/networking/requests/messages/player_help_info_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/networking/requests/messages/player_help_info_message.proto',
  package='wuprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nDwuprotos/networking/requests/messages/player_help_info_message.proto\x12%wuprotos.networking.requests.messages\"\x17\n\x15PlayerHelpInfoMessageb\x06proto3')
)




_PLAYERHELPINFOMESSAGE = _descriptor.Descriptor(
  name='PlayerHelpInfoMessage',
  full_name='wuprotos.networking.requests.messages.PlayerHelpInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['PlayerHelpInfoMessage'] = _PLAYERHELPINFOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerHelpInfoMessage = _reflection.GeneratedProtocolMessageType('PlayerHelpInfoMessage', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERHELPINFOMESSAGE,
  __module__ = 'wuprotos.networking.requests.messages.player_help_info_message_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.networking.requests.messages.PlayerHelpInfoMessage)
  ))
_sym_db.RegisterMessage(PlayerHelpInfoMessage)


# @@protoc_insertion_point(module_scope)
