# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Requests/Messages/ProfanityFilterMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Requests/Messages/ProfanityFilterMessage.proto',
  package='WUProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nBWUProtos/Networking/Requests/Messages/ProfanityFilterMessage.proto\x12%WUProtos.Networking.Requests.Messages\"&\n\x16ProfanityFilterMessage\x12\x0c\n\x04text\x18\x01 \x03(\tb\x06proto3')
)




_PROFANITYFILTERMESSAGE = _descriptor.Descriptor(
  name='ProfanityFilterMessage',
  full_name='WUProtos.Networking.Requests.Messages.ProfanityFilterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='WUProtos.Networking.Requests.Messages.ProfanityFilterMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['ProfanityFilterMessage'] = _PROFANITYFILTERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProfanityFilterMessage = _reflection.GeneratedProtocolMessageType('ProfanityFilterMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROFANITYFILTERMESSAGE,
  __module__ = 'WUProtos.Networking.Requests.Messages.ProfanityFilterMessage_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Requests.Messages.ProfanityFilterMessage)
  ))
_sym_db.RegisterMessage(ProfanityFilterMessage)


# @@protoc_insertion_point(module_scope)
