# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Networking/Requests/Messages/UpdateProfileFieldMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Enums import ProfileFieldOperation_pb2 as WUProtos_dot_Enums_dot_ProfileFieldOperation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Networking/Requests/Messages/UpdateProfileFieldMessage.proto',
  package='WUProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nEWUProtos/Networking/Requests/Messages/UpdateProfileFieldMessage.proto\x12%WUProtos.Networking.Requests.Messages\x1a*WUProtos/Enums/ProfileFieldOperation.proto\"\xe0\x01\n\x19UpdateProfileFieldMessage\x12\x64\n\x07updates\x18\x01 \x03(\x0b\x32S.WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage.ProfileFieldUpdate\x1a]\n\x12ProfileFieldUpdate\x12\x38\n\toperation\x18\x01 \x01(\x0e\x32%.WUProtos.Enums.ProfileFieldOperation\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Enums_dot_ProfileFieldOperation__pb2.DESCRIPTOR,])




_UPDATEPROFILEFIELDMESSAGE_PROFILEFIELDUPDATE = _descriptor.Descriptor(
  name='ProfileFieldUpdate',
  full_name='WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage.ProfileFieldUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage.ProfileFieldUpdate.operation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage.ProfileFieldUpdate.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=381,
)

_UPDATEPROFILEFIELDMESSAGE = _descriptor.Descriptor(
  name='UpdateProfileFieldMessage',
  full_name='WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='updates', full_name='WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage.updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATEPROFILEFIELDMESSAGE_PROFILEFIELDUPDATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=381,
)

_UPDATEPROFILEFIELDMESSAGE_PROFILEFIELDUPDATE.fields_by_name['operation'].enum_type = WUProtos_dot_Enums_dot_ProfileFieldOperation__pb2._PROFILEFIELDOPERATION
_UPDATEPROFILEFIELDMESSAGE_PROFILEFIELDUPDATE.containing_type = _UPDATEPROFILEFIELDMESSAGE
_UPDATEPROFILEFIELDMESSAGE.fields_by_name['updates'].message_type = _UPDATEPROFILEFIELDMESSAGE_PROFILEFIELDUPDATE
DESCRIPTOR.message_types_by_name['UpdateProfileFieldMessage'] = _UPDATEPROFILEFIELDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateProfileFieldMessage = _reflection.GeneratedProtocolMessageType('UpdateProfileFieldMessage', (_message.Message,), dict(

  ProfileFieldUpdate = _reflection.GeneratedProtocolMessageType('ProfileFieldUpdate', (_message.Message,), dict(
    DESCRIPTOR = _UPDATEPROFILEFIELDMESSAGE_PROFILEFIELDUPDATE,
    __module__ = 'WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage_pb2'
    # @@protoc_insertion_point(class_scope:WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage.ProfileFieldUpdate)
    ))
  ,
  DESCRIPTOR = _UPDATEPROFILEFIELDMESSAGE,
  __module__ = 'WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Networking.Requests.Messages.UpdateProfileFieldMessage)
  ))
_sym_db.RegisterMessage(UpdateProfileFieldMessage)
_sym_db.RegisterMessage(UpdateProfileFieldMessage.ProfileFieldUpdate)


# @@protoc_insertion_point(module_scope)
