# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Combat/CombatState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Combat import CombatMoveType_pb2 as WUProtos_dot_Data_dot_Combat_dot_CombatMoveType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Combat/CombatState.proto',
  package='WUProtos.Data.Combat',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&WUProtos/Data/Combat/CombatState.proto\x12\x14WUProtos.Data.Combat\x1a)WUProtos/Data/Combat/CombatMoveType.proto\"K\n\x0b\x43ombatState\x12<\n\x0epossible_moves\x18\x01 \x03(\x0b\x32$.WUProtos.Data.Combat.CombatMoveTypeb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Combat_dot_CombatMoveType__pb2.DESCRIPTOR,])




_COMBATSTATE = _descriptor.Descriptor(
  name='CombatState',
  full_name='WUProtos.Data.Combat.CombatState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='possible_moves', full_name='WUProtos.Data.Combat.CombatState.possible_moves', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=182,
)

_COMBATSTATE.fields_by_name['possible_moves'].message_type = WUProtos_dot_Data_dot_Combat_dot_CombatMoveType__pb2._COMBATMOVETYPE
DESCRIPTOR.message_types_by_name['CombatState'] = _COMBATSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CombatState = _reflection.GeneratedProtocolMessageType('CombatState', (_message.Message,), dict(
  DESCRIPTOR = _COMBATSTATE,
  __module__ = 'WUProtos.Data.Combat.CombatState_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Combat.CombatState)
  ))
_sym_db.RegisterMessage(CombatState)


# @@protoc_insertion_point(module_scope)
