# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Buff/PermanentBuffExpiration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Buff/PermanentBuffExpiration.proto',
  package='WUProtos.Data.Buff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n0WUProtos/Data/Buff/PermanentBuffExpiration.proto\x12\x12WUProtos.Data.Buff\"\x19\n\x17PermanentBuffExpirationb\x06proto3')
)




_PERMANENTBUFFEXPIRATION = _descriptor.Descriptor(
  name='PermanentBuffExpiration',
  full_name='WUProtos.Data.Buff.PermanentBuffExpiration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['PermanentBuffExpiration'] = _PERMANENTBUFFEXPIRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PermanentBuffExpiration = _reflection.GeneratedProtocolMessageType('PermanentBuffExpiration', (_message.Message,), dict(
  DESCRIPTOR = _PERMANENTBUFFEXPIRATION,
  __module__ = 'WUProtos.Data.Buff.PermanentBuffExpiration_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Buff.PermanentBuffExpiration)
  ))
_sym_db.RegisterMessage(PermanentBuffExpiration)


# @@protoc_insertion_point(module_scope)
