# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Potion/PotionVaultItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Enums import PotionConsumableScenario_pb2 as WUProtos_dot_Enums_dot_PotionConsumableScenario__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Potion/PotionVaultItem.proto',
  package='WUProtos.Data.Potion',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*WUProtos/Data/Potion/PotionVaultItem.proto\x12\x14WUProtos.Data.Potion\x1a-WUProtos/Enums/PotionConsumableScenario.proto\"u\n\x0fPotionVaultItem\x12\x45\n\x13\x63onsumable_scenario\x18\x03 \x03(\x0e\x32(.WUProtos.Enums.PotionConsumableScenario\x12\x1b\n\x13\x61pplied_buff_gmt_id\x18\x04 \x03(\tb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Enums_dot_PotionConsumableScenario__pb2.DESCRIPTOR,])




_POTIONVAULTITEM = _descriptor.Descriptor(
  name='PotionVaultItem',
  full_name='WUProtos.Data.Potion.PotionVaultItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumable_scenario', full_name='WUProtos.Data.Potion.PotionVaultItem.consumable_scenario', index=0,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applied_buff_gmt_id', full_name='WUProtos.Data.Potion.PotionVaultItem.applied_buff_gmt_id', index=1,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=232,
)

_POTIONVAULTITEM.fields_by_name['consumable_scenario'].enum_type = WUProtos_dot_Enums_dot_PotionConsumableScenario__pb2._POTIONCONSUMABLESCENARIO
DESCRIPTOR.message_types_by_name['PotionVaultItem'] = _POTIONVAULTITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PotionVaultItem = _reflection.GeneratedProtocolMessageType('PotionVaultItem', (_message.Message,), dict(
  DESCRIPTOR = _POTIONVAULTITEM,
  __module__ = 'WUProtos.Data.Potion.PotionVaultItem_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Potion.PotionVaultItem)
  ))
_sym_db.RegisterMessage(PotionVaultItem)


# @@protoc_insertion_point(module_scope)
