# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Encounter/EncounterStartCombatStageResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Encounter/EncounterStartCombatStageResult.proto',
  package='WUProtos.Data.Encounter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n=WUProtos/Data/Encounter/EncounterStartCombatStageResult.proto\x12\x17WUProtos.Data.Encounter\"\xe1\x02\n\x1f\x45ncounterStartCombatStageResult\x12\x14\n\x0chp_max_enemy\x18\x01 \x01(\x03\x12\x1e\n\x16\x65nemy_damage_unblocked\x18\x02 \x03(\x03\x12\x1c\n\x14\x65nemy_damage_blocked\x18\x03 \x03(\x03\x12\x15\n\rhp_max_player\x18\x04 \x01(\x03\x12u\n\x18player_damage_per_energy\x18\x05 \x03(\x0b\x32S.WUProtos.Data.Encounter.EncounterStartCombatStageResult.PlayerDamagePerEnergyEntry\x12\x1e\n\x16player_crit_multiplier\x18\x06 \x01(\x02\x1a<\n\x1aPlayerDamagePerEnergyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')
)




_ENCOUNTERSTARTCOMBATSTAGERESULT_PLAYERDAMAGEPERENERGYENTRY = _descriptor.Descriptor(
  name='PlayerDamagePerEnergyEntry',
  full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.PlayerDamagePerEnergyEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.PlayerDamagePerEnergyEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.PlayerDamagePerEnergyEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=444,
)

_ENCOUNTERSTARTCOMBATSTAGERESULT = _descriptor.Descriptor(
  name='EncounterStartCombatStageResult',
  full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hp_max_enemy', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.hp_max_enemy', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemy_damage_unblocked', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.enemy_damage_unblocked', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemy_damage_blocked', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.enemy_damage_blocked', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hp_max_player', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.hp_max_player', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_damage_per_energy', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.player_damage_per_energy', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_crit_multiplier', full_name='WUProtos.Data.Encounter.EncounterStartCombatStageResult.player_crit_multiplier', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENCOUNTERSTARTCOMBATSTAGERESULT_PLAYERDAMAGEPERENERGYENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=444,
)

_ENCOUNTERSTARTCOMBATSTAGERESULT_PLAYERDAMAGEPERENERGYENTRY.containing_type = _ENCOUNTERSTARTCOMBATSTAGERESULT
_ENCOUNTERSTARTCOMBATSTAGERESULT.fields_by_name['player_damage_per_energy'].message_type = _ENCOUNTERSTARTCOMBATSTAGERESULT_PLAYERDAMAGEPERENERGYENTRY
DESCRIPTOR.message_types_by_name['EncounterStartCombatStageResult'] = _ENCOUNTERSTARTCOMBATSTAGERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncounterStartCombatStageResult = _reflection.GeneratedProtocolMessageType('EncounterStartCombatStageResult', (_message.Message,), dict(

  PlayerDamagePerEnergyEntry = _reflection.GeneratedProtocolMessageType('PlayerDamagePerEnergyEntry', (_message.Message,), dict(
    DESCRIPTOR = _ENCOUNTERSTARTCOMBATSTAGERESULT_PLAYERDAMAGEPERENERGYENTRY,
    __module__ = 'WUProtos.Data.Encounter.EncounterStartCombatStageResult_pb2'
    # @@protoc_insertion_point(class_scope:WUProtos.Data.Encounter.EncounterStartCombatStageResult.PlayerDamagePerEnergyEntry)
    ))
  ,
  DESCRIPTOR = _ENCOUNTERSTARTCOMBATSTAGERESULT,
  __module__ = 'WUProtos.Data.Encounter.EncounterStartCombatStageResult_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Encounter.EncounterStartCombatStageResult)
  ))
_sym_db.RegisterMessage(EncounterStartCombatStageResult)
_sym_db.RegisterMessage(EncounterStartCombatStageResult.PlayerDamagePerEnergyEntry)


_ENCOUNTERSTARTCOMBATSTAGERESULT_PLAYERDAMAGEPERENERGYENTRY._options = None
# @@protoc_insertion_point(module_scope)
