# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wuprotos/data/player/player_professions_progress_v3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wuprotos/data/player/player_professions_progress_v3.proto',
  package='wuprotos.data.player',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n9wuprotos/data/player/player_professions_progress_v3.proto\x12\x14wuprotos.data.player\"\x1d\n\x1bPlayerProfessionsProgressV3b\x06proto3')
)




_PLAYERPROFESSIONSPROGRESSV3 = _descriptor.Descriptor(
  name='PlayerProfessionsProgressV3',
  full_name='wuprotos.data.player.PlayerProfessionsProgressV3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['PlayerProfessionsProgressV3'] = _PLAYERPROFESSIONSPROGRESSV3
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerProfessionsProgressV3 = _reflection.GeneratedProtocolMessageType('PlayerProfessionsProgressV3', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERPROFESSIONSPROGRESSV3,
  __module__ = 'wuprotos.data.player.player_professions_progress_v3_pb2'
  # @@protoc_insertion_point(class_scope:wuprotos.data.player.PlayerProfessionsProgressV3)
  ))
_sym_db.RegisterMessage(PlayerProfessionsProgressV3)


# @@protoc_insertion_point(module_scope)
