# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Player/PlayerAchievement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Player/PlayerAchievement.proto',
  package='WUProtos.Data.Player',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,WUProtos/Data/Player/PlayerAchievement.proto\x12\x14WUProtos.Data.Player\"\x13\n\x11PlayerAchievementb\x06proto3')
)




_PLAYERACHIEVEMENT = _descriptor.Descriptor(
  name='PlayerAchievement',
  full_name='WUProtos.Data.Player.PlayerAchievement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['PlayerAchievement'] = _PLAYERACHIEVEMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerAchievement = _reflection.GeneratedProtocolMessageType('PlayerAchievement', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERACHIEVEMENT,
  __module__ = 'WUProtos.Data.Player.PlayerAchievement_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Player.PlayerAchievement)
  ))
_sym_db.RegisterMessage(PlayerAchievement)


# @@protoc_insertion_point(module_scope)
