# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Telemetry/PlatformEventData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from WUProtos.Data.Telemetry import TelemetryCommon_pb2 as WUProtos_dot_Data_dot_Telemetry_dot_TelemetryCommon__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Telemetry/PlatformEventData.proto',
  package='WUProtos.Data.Telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/WUProtos/Data/Telemetry/PlatformEventData.proto\x12\x17WUProtos.Data.Telemetry\x1a-WUProtos/Data/Telemetry/TelemetryCommon.proto\"W\n\x11PlatformEventData\x12\x42\n\x10\x63ommon_telemetry\x18\x01 \x01(\x0b\x32(.WUProtos.Data.Telemetry.TelemetryCommonb\x06proto3')
  ,
  dependencies=[WUProtos_dot_Data_dot_Telemetry_dot_TelemetryCommon__pb2.DESCRIPTOR,])




_PLATFORMEVENTDATA = _descriptor.Descriptor(
  name='PlatformEventData',
  full_name='WUProtos.Data.Telemetry.PlatformEventData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_telemetry', full_name='WUProtos.Data.Telemetry.PlatformEventData.common_telemetry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=210,
)

_PLATFORMEVENTDATA.fields_by_name['common_telemetry'].message_type = WUProtos_dot_Data_dot_Telemetry_dot_TelemetryCommon__pb2._TELEMETRYCOMMON
DESCRIPTOR.message_types_by_name['PlatformEventData'] = _PLATFORMEVENTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlatformEventData = _reflection.GeneratedProtocolMessageType('PlatformEventData', (_message.Message,), dict(
  DESCRIPTOR = _PLATFORMEVENTDATA,
  __module__ = 'WUProtos.Data.Telemetry.PlatformEventData_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Telemetry.PlatformEventData)
  ))
_sym_db.RegisterMessage(PlatformEventData)


# @@protoc_insertion_point(module_scope)
