# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WUProtos/Data/Challenge/ChallengeBuffExpiration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WUProtos/Data/Challenge/ChallengeBuffExpiration.proto',
  package='WUProtos.Data.Challenge',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n5WUProtos/Data/Challenge/ChallengeBuffExpiration.proto\x12\x17WUProtos.Data.Challenge\"\x19\n\x17\x43hallengeBuffExpirationb\x06proto3')
)




_CHALLENGEBUFFEXPIRATION = _descriptor.Descriptor(
  name='ChallengeBuffExpiration',
  full_name='WUProtos.Data.Challenge.ChallengeBuffExpiration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['ChallengeBuffExpiration'] = _CHALLENGEBUFFEXPIRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChallengeBuffExpiration = _reflection.GeneratedProtocolMessageType('ChallengeBuffExpiration', (_message.Message,), dict(
  DESCRIPTOR = _CHALLENGEBUFFEXPIRATION,
  __module__ = 'WUProtos.Data.Challenge.ChallengeBuffExpiration_pb2'
  # @@protoc_insertion_point(class_scope:WUProtos.Data.Challenge.ChallengeBuffExpiration)
  ))
_sym_db.RegisterMessage(ChallengeBuffExpiration)


# @@protoc_insertion_point(module_scope)
